module VitablePartnerAPI
  module Models
    type benefit_product =
      {
        id: String,
        name: String,
        product_type: String,
        plans: ::Array[VitablePartnerAPI::Plan]
      }

    class BenefitProduct < VitablePartnerAPI::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor name: String

      attr_accessor product_type: String

      attr_reader plans: ::Array[VitablePartnerAPI::Plan]?

      def plans=: (
        ::Array[VitablePartnerAPI::Plan]
      ) -> ::Array[VitablePartnerAPI::Plan]

      def initialize: (
        id: String,
        name: String,
        product_type: String,
        ?plans: ::Array[VitablePartnerAPI::Plan]
      ) -> void

      def to_hash: -> {
        id: String,
        name: String,
        product_type: String,
        plans: ::Array[VitablePartnerAPI::Plan]
      }
    end
  end
end
