module VitablePartnerAPI
  module Models
    type benefit_product_generate_quote_params =
      {  } & VitablePartnerAPI::Internal::Type::request_parameters

    class BenefitProductGenerateQuoteParams < VitablePartnerAPI::Models::QuoteRequest
      extend VitablePartnerAPI::Internal::Type::RequestParameters::Converter
      include VitablePartnerAPI::Internal::Type::RequestParameters

      def initialize: (
        ?request_options: VitablePartnerAPI::request_opts
      ) -> void

      def to_hash: -> { request_options: VitablePartnerAPI::RequestOptions }
    end
  end
end
