module VitablePartnerAPI
  module Models
    type create_eligibility_policy_request =
      {
        classification: VitablePartnerAPI::Models::CreateEligibilityPolicyRequest::classification,
        waiting_period: VitablePartnerAPI::Models::CreateEligibilityPolicyRequest::waiting_period
      }

    class CreateEligibilityPolicyRequest < VitablePartnerAPI::Internal::Type::BaseModel
      attr_accessor classification: VitablePartnerAPI::Models::CreateEligibilityPolicyRequest::classification

      attr_accessor waiting_period: VitablePartnerAPI::Models::CreateEligibilityPolicyRequest::waiting_period

      def initialize: (
        classification: VitablePartnerAPI::Models::CreateEligibilityPolicyRequest::classification,
        waiting_period: VitablePartnerAPI::Models::CreateEligibilityPolicyRequest::waiting_period
      ) -> void

      def to_hash: -> {
        classification: VitablePartnerAPI::Models::CreateEligibilityPolicyRequest::classification,
        waiting_period: VitablePartnerAPI::Models::CreateEligibilityPolicyRequest::waiting_period
      }

      type classification = :FULL_TIME | :PART_TIME | :ALL

      module Classification
        extend VitablePartnerAPI::Internal::Type::Enum

        FULL_TIME: :FULL_TIME
        PART_TIME: :PART_TIME
        ALL: :ALL

        def self?.values: -> ::Array[VitablePartnerAPI::Models::CreateEligibilityPolicyRequest::classification]
      end

      type waiting_period =
        :FIRST_OF_FOLLOWING_MONTH | :THIRTY_DAYS | :SIXTY_DAYS | :NONE

      module WaitingPeriod
        extend VitablePartnerAPI::Internal::Type::Enum

        FIRST_OF_FOLLOWING_MONTH: :FIRST_OF_FOLLOWING_MONTH
        THIRTY_DAYS: :THIRTY_DAYS
        SIXTY_DAYS: :SIXTY_DAYS
        NONE: :NONE

        def self?.values: -> ::Array[VitablePartnerAPI::Models::CreateEligibilityPolicyRequest::waiting_period]
      end
    end
  end
end
