module VitablePartnerAPI
  module Models
    type dependent =
      { relationship: VitablePartnerAPI::Models::Dependent::relationship }

    class Dependent < VitablePartnerAPI::Models::Member
      def relationship: -> VitablePartnerAPI::Models::Dependent::relationship

      def relationship=: (
        VitablePartnerAPI::Models::Dependent::relationship _
      ) -> VitablePartnerAPI::Models::Dependent::relationship

      def initialize: (
        relationship: VitablePartnerAPI::Models::Dependent::relationship
      ) -> void

      def to_hash: -> {
        relationship: VitablePartnerAPI::Models::Dependent::relationship
      }

      type relationship = :SPOUSE | :CHILD

      module Relationship
        extend VitablePartnerAPI::Internal::Type::Enum

        SPOUSE: :SPOUSE
        CHILD: :CHILD

        def self?.values: -> ::Array[VitablePartnerAPI::Models::Dependent::relationship]
      end
    end
  end
end
