module VitablePartnerAPI
  module Models
    type elect_benefits_request =
      { elections: ::Array[VitablePartnerAPI::ElectBenefitsRequest::Election] }

    class ElectBenefitsRequest < VitablePartnerAPI::Internal::Type::BaseModel
      attr_accessor elections: ::Array[VitablePartnerAPI::ElectBenefitsRequest::Election]

      def initialize: (
        elections: ::Array[VitablePartnerAPI::ElectBenefitsRequest::Election]
      ) -> void

      def to_hash: -> {
        elections: ::Array[VitablePartnerAPI::ElectBenefitsRequest::Election]
      }

      type election =
        {
          decision: VitablePartnerAPI::Models::ElectBenefitsRequest::Election::decision,
          enrollment_id: String,
          dependent_ids: ::Array[String],
          plan_id: String
        }

      class Election < VitablePartnerAPI::Internal::Type::BaseModel
        attr_accessor decision: VitablePartnerAPI::Models::ElectBenefitsRequest::Election::decision

        attr_accessor enrollment_id: String

        attr_reader dependent_ids: ::Array[String]?

        def dependent_ids=: (::Array[String]) -> ::Array[String]

        attr_reader plan_id: String?

        def plan_id=: (String) -> String

        def initialize: (
          decision: VitablePartnerAPI::Models::ElectBenefitsRequest::Election::decision,
          enrollment_id: String,
          ?dependent_ids: ::Array[String],
          ?plan_id: String
        ) -> void

        def to_hash: -> {
          decision: VitablePartnerAPI::Models::ElectBenefitsRequest::Election::decision,
          enrollment_id: String,
          dependent_ids: ::Array[String],
          plan_id: String
        }

        type decision = :enrolled | :waived

        module Decision
          extend VitablePartnerAPI::Internal::Type::Enum

          ENROLLED: :enrolled
          WAIVED: :waived

          def self?.values: -> ::Array[VitablePartnerAPI::Models::ElectBenefitsRequest::Election::decision]
        end
      end
    end
  end
end
