module VitablePartnerAPI
  module Models
    type eligibility_policy =
      {
        id: String,
        active: bool,
        classification: VitablePartnerAPI::Models::EligibilityPolicy::classification,
        employer_id: String,
        waiting_period: VitablePartnerAPI::Models::EligibilityPolicy::waiting_period,
        archived_at: Time?,
        replaces_policy_id: String?
      }

    class EligibilityPolicy < VitablePartnerAPI::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor active: bool

      attr_accessor classification: VitablePartnerAPI::Models::EligibilityPolicy::classification

      attr_accessor employer_id: String

      attr_accessor waiting_period: VitablePartnerAPI::Models::EligibilityPolicy::waiting_period

      attr_accessor archived_at: Time?

      attr_accessor replaces_policy_id: String?

      def initialize: (
        id: String,
        active: bool,
        classification: VitablePartnerAPI::Models::EligibilityPolicy::classification,
        employer_id: String,
        waiting_period: VitablePartnerAPI::Models::EligibilityPolicy::waiting_period,
        ?archived_at: Time?,
        ?replaces_policy_id: String?
      ) -> void

      def to_hash: -> {
        id: String,
        active: bool,
        classification: VitablePartnerAPI::Models::EligibilityPolicy::classification,
        employer_id: String,
        waiting_period: VitablePartnerAPI::Models::EligibilityPolicy::waiting_period,
        archived_at: Time?,
        replaces_policy_id: String?
      }

      type classification = :FULL_TIME | :PART_TIME | :ALL

      module Classification
        extend VitablePartnerAPI::Internal::Type::Enum

        FULL_TIME: :FULL_TIME
        PART_TIME: :PART_TIME
        ALL: :ALL

        def self?.values: -> ::Array[VitablePartnerAPI::Models::EligibilityPolicy::classification]
      end

      type waiting_period =
        :FIRST_OF_FOLLOWING_MONTH | :THIRTY_DAYS | :SIXTY_DAYS | :NONE

      module WaitingPeriod
        extend VitablePartnerAPI::Internal::Type::Enum

        FIRST_OF_FOLLOWING_MONTH: :FIRST_OF_FOLLOWING_MONTH
        THIRTY_DAYS: :THIRTY_DAYS
        SIXTY_DAYS: :SIXTY_DAYS
        NONE: :NONE

        def self?.values: -> ::Array[VitablePartnerAPI::Models::EligibilityPolicy::waiting_period]
      end
    end
  end
end
