module VitablePartnerAPI
  module Models
    type employee_terminate_params =
      {  } & VitablePartnerAPI::Internal::Type::request_parameters

    class EmployeeTerminateParams < VitablePartnerAPI::Internal::Type::BaseModel
      extend VitablePartnerAPI::Internal::Type::RequestParameters::Converter
      include VitablePartnerAPI::Internal::Type::RequestParameters

      def initialize: (
        ?request_options: VitablePartnerAPI::request_opts
      ) -> void

      def to_hash: -> { request_options: VitablePartnerAPI::RequestOptions }
    end
  end
end
