module VitablePartnerAPI
  module Models
    type employee_update_params =
      {  } & VitablePartnerAPI::Internal::Type::request_parameters

    class EmployeeUpdateParams < VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest
      extend VitablePartnerAPI::Internal::Type::RequestParameters::Converter
      include VitablePartnerAPI::Internal::Type::RequestParameters

      def initialize: (
        ?request_options: VitablePartnerAPI::request_opts
      ) -> void

      def to_hash: -> { request_options: VitablePartnerAPI::RequestOptions }
    end
  end
end
