module VitablePartnerAPI
  module Models
    type enrollment_get_eligible_plans_response =
      { data: ::Array[VitablePartnerAPI::Plan] }

    class EnrollmentGetEligiblePlansResponse < VitablePartnerAPI::Internal::Type::BaseModel
      attr_reader data: ::Array[VitablePartnerAPI::Plan]?

      def data=: (
        ::Array[VitablePartnerAPI::Plan]
      ) -> ::Array[VitablePartnerAPI::Plan]

      def initialize: (?data: ::Array[VitablePartnerAPI::Plan]) -> void

      def to_hash: -> { data: ::Array[VitablePartnerAPI::Plan] }
    end
  end
end
