module VitablePartnerAPI
  module Models
    type plan_year =
      {
        id: String,
        benefit_product: VitablePartnerAPI::BenefitProduct,
        configured: bool,
        coverage_end_date: Date,
        coverage_start_date: Date,
        employer_id: String,
        open_enrollment_end_date: Date,
        open_enrollment_start_date: Date,
        contribution_classes: ::Array[VitablePartnerAPI::BenefitProducts::PlanContributionClass],
        plan_costs: ::Array[VitablePartnerAPI::BenefitProducts::PlanCost]
      }

    class PlanYear < VitablePartnerAPI::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor benefit_product: VitablePartnerAPI::BenefitProduct

      attr_accessor configured: bool

      attr_accessor coverage_end_date: Date

      attr_accessor coverage_start_date: Date

      attr_accessor employer_id: String

      attr_accessor open_enrollment_end_date: Date

      attr_accessor open_enrollment_start_date: Date

      attr_reader contribution_classes: ::Array[VitablePartnerAPI::BenefitProducts::PlanContributionClass]?

      def contribution_classes=: (
        ::Array[VitablePartnerAPI::BenefitProducts::PlanContributionClass]
      ) -> ::Array[VitablePartnerAPI::BenefitProducts::PlanContributionClass]

      attr_reader plan_costs: ::Array[VitablePartnerAPI::BenefitProducts::PlanCost]?

      def plan_costs=: (
        ::Array[VitablePartnerAPI::BenefitProducts::PlanCost]
      ) -> ::Array[VitablePartnerAPI::BenefitProducts::PlanCost]

      def initialize: (
        id: String,
        benefit_product: VitablePartnerAPI::BenefitProduct,
        configured: bool,
        coverage_end_date: Date,
        coverage_start_date: Date,
        employer_id: String,
        open_enrollment_end_date: Date,
        open_enrollment_start_date: Date,
        ?contribution_classes: ::Array[VitablePartnerAPI::BenefitProducts::PlanContributionClass],
        ?plan_costs: ::Array[VitablePartnerAPI::BenefitProducts::PlanCost]
      ) -> void

      def to_hash: -> {
        id: String,
        benefit_product: VitablePartnerAPI::BenefitProduct,
        configured: bool,
        coverage_end_date: Date,
        coverage_start_date: Date,
        employer_id: String,
        open_enrollment_end_date: Date,
        open_enrollment_start_date: Date,
        contribution_classes: ::Array[VitablePartnerAPI::BenefitProducts::PlanContributionClass],
        plan_costs: ::Array[VitablePartnerAPI::BenefitProducts::PlanCost]
      }
    end
  end
end
