module VitablePartnerAPI
  module Models
    type quote =
      {
        benefit_product_id: String,
        employer_id: String,
        total_cost_in_cents: Integer,
        breakdown: ::Hash[Symbol, top]
      }

    class Quote < VitablePartnerAPI::Internal::Type::BaseModel
      attr_accessor benefit_product_id: String

      attr_accessor employer_id: String

      attr_accessor total_cost_in_cents: Integer

      attr_reader breakdown: ::Hash[Symbol, top]?

      def breakdown=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      def initialize: (
        benefit_product_id: String,
        employer_id: String,
        total_cost_in_cents: Integer,
        ?breakdown: ::Hash[Symbol, top]
      ) -> void

      def to_hash: -> {
        benefit_product_id: String,
        employer_id: String,
        total_cost_in_cents: Integer,
        breakdown: ::Hash[Symbol, top]
      }
    end
  end
end
