module VitablePartnerAPI
  module Models
    type update_employer_request =
      { active: bool, legal_name: String, name: String }

    class UpdateEmployerRequest < VitablePartnerAPI::Internal::Type::BaseModel
      attr_reader active: bool?

      def active=: (bool) -> bool

      attr_reader legal_name: String?

      def legal_name=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      def initialize: (
        ?active: bool,
        ?legal_name: String,
        ?name: String
      ) -> void

      def to_hash: -> { active: bool, legal_name: String, name: String }
    end
  end
end
