module VitableConnect
  module Models
    module BenefitProducts
      type plan_year_response =
        { data: VitableConnect::BenefitProducts::PlanYear }

      class PlanYearResponse < VitableConnect::Internal::Type::BaseModel
        attr_accessor data: VitableConnect::BenefitProducts::PlanYear

        def initialize: (
          data: VitableConnect::BenefitProducts::PlanYear
        ) -> void

        def to_hash: -> { data: VitableConnect::BenefitProducts::PlanYear }
      end
    end
  end
end
