module VitableConnect
  module Models
    module BenefitProducts
      type plan_year_status = :draft | :open_enrollment | :active | :expired

      module PlanYearStatus
        extend VitableConnect::Internal::Type::Enum

        DRAFT: :draft
        OPEN_ENROLLMENT: :open_enrollment
        ACTIVE: :active
        EXPIRED: :expired

        def self?.values: -> ::Array[VitableConnect::Models::BenefitProducts::plan_year_status]
      end
    end
  end
end
