module VitableConnect
  module Models
    module BenefitProducts
      type plan_year_list_response =
        {
          data: ::Array[VitableConnect::BenefitProducts::PlanYear],
          pagination: VitableConnect::Pagination
        }

      class PlanYearListResponse < VitableConnect::Internal::Type::BaseModel
        attr_accessor data: ::Array[VitableConnect::BenefitProducts::PlanYear]

        attr_accessor pagination: VitableConnect::Pagination

        def initialize: (
          data: ::Array[VitableConnect::BenefitProducts::PlanYear],
          pagination: VitableConnect::Pagination
        ) -> void

        def to_hash: -> {
          data: ::Array[VitableConnect::BenefitProducts::PlanYear],
          pagination: VitableConnect::Pagination
        }
      end
    end
  end
end
