module VitableConnect
  module Models
    module BenefitProducts
      type plan_year_list_params =
        {
          employer_id: String,
          limit: Integer,
          page: Integer,
          status: VitableConnect::Models::BenefitProducts::plan_year_status
        }
        & VitableConnect::Internal::Type::request_parameters

      class PlanYearListParams < VitableConnect::Internal::Type::BaseModel
        extend VitableConnect::Internal::Type::RequestParameters::Converter
        include VitableConnect::Internal::Type::RequestParameters

        attr_reader employer_id: String?

        def employer_id=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader page: Integer?

        def page=: (Integer) -> Integer

        attr_reader status: VitableConnect::Models::BenefitProducts::plan_year_status?

        def status=: (
          VitableConnect::Models::BenefitProducts::plan_year_status
        ) -> VitableConnect::Models::BenefitProducts::plan_year_status

        def initialize: (
          ?employer_id: String,
          ?limit: Integer,
          ?page: Integer,
          ?status: VitableConnect::Models::BenefitProducts::plan_year_status,
          ?request_options: VitableConnect::request_opts
        ) -> void

        def to_hash: -> {
          employer_id: String,
          limit: Integer,
          page: Integer,
          status: VitableConnect::Models::BenefitProducts::plan_year_status,
          request_options: VitableConnect::RequestOptions
        }
      end
    end
  end
end
