module VitableConnect
  module Models
    module BenefitProducts
      type plan_year =
        {
          id: String,
          benefit_product_id: String,
          contribution_classes: ::Array[VitableConnect::BenefitProducts::PlanYear::ContributionClass],
          coverage_end: Date,
          coverage_start: Date,
          created_at: Time,
          employer_id: String,
          open_enrollment_end_date: Date,
          open_enrollment_start_date: Date,
          plans: ::Array[VitableConnect::BenefitProducts::PlanYear::Plan],
          status: VitableConnect::Models::BenefitProducts::plan_year_status,
          updated_at: Time
        }

      class PlanYear < VitableConnect::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor benefit_product_id: String

        attr_accessor contribution_classes: ::Array[VitableConnect::BenefitProducts::PlanYear::ContributionClass]

        attr_accessor coverage_end: Date

        attr_accessor coverage_start: Date

        attr_accessor created_at: Time

        attr_accessor employer_id: String

        attr_accessor open_enrollment_end_date: Date

        attr_accessor open_enrollment_start_date: Date

        attr_accessor plans: ::Array[VitableConnect::BenefitProducts::PlanYear::Plan]

        attr_accessor status: VitableConnect::Models::BenefitProducts::plan_year_status

        attr_accessor updated_at: Time

        def initialize: (
          id: String,
          benefit_product_id: String,
          contribution_classes: ::Array[VitableConnect::BenefitProducts::PlanYear::ContributionClass],
          coverage_end: Date,
          coverage_start: Date,
          created_at: Time,
          employer_id: String,
          open_enrollment_end_date: Date,
          open_enrollment_start_date: Date,
          plans: ::Array[VitableConnect::BenefitProducts::PlanYear::Plan],
          status: VitableConnect::Models::BenefitProducts::plan_year_status,
          updated_at: Time
        ) -> void

        def to_hash: -> {
          id: String,
          benefit_product_id: String,
          contribution_classes: ::Array[VitableConnect::BenefitProducts::PlanYear::ContributionClass],
          coverage_end: Date,
          coverage_start: Date,
          created_at: Time,
          employer_id: String,
          open_enrollment_end_date: Date,
          open_enrollment_start_date: Date,
          plans: ::Array[VitableConnect::BenefitProducts::PlanYear::Plan],
          status: VitableConnect::Models::BenefitProducts::plan_year_status,
          updated_at: Time
        }

        type contribution_class =
          {
            id: String,
            coverage_tier: VitableConnect::Models::coverage_tier,
            employee_contribution_cents: Integer,
            employer_contribution_cents: Integer,
            employment: String
          }

        class ContributionClass < VitableConnect::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor coverage_tier: VitableConnect::Models::coverage_tier

          attr_accessor employee_contribution_cents: Integer

          attr_accessor employer_contribution_cents: Integer

          attr_accessor employment: String

          def initialize: (
            id: String,
            coverage_tier: VitableConnect::Models::coverage_tier,
            employee_contribution_cents: Integer,
            employer_contribution_cents: Integer,
            employment: String
          ) -> void

          def to_hash: -> {
            id: String,
            coverage_tier: VitableConnect::Models::coverage_tier,
            employee_contribution_cents: Integer,
            employer_contribution_cents: Integer,
            employment: String
          }
        end

        type plan =
          {
            id: String,
            carrier_plan_id: String,
            monthly_premium_cents: Integer,
            name: String,
            deductible_cents: Integer?,
            out_of_pocket_max_cents: Integer?,
            tier: VitableConnect::Models::plan_tier?
          }

        class Plan < VitableConnect::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor carrier_plan_id: String

          attr_accessor monthly_premium_cents: Integer

          attr_accessor name: String

          attr_accessor deductible_cents: Integer?

          attr_accessor out_of_pocket_max_cents: Integer?

          attr_accessor tier: VitableConnect::Models::plan_tier?

          def initialize: (
            id: String,
            carrier_plan_id: String,
            monthly_premium_cents: Integer,
            name: String,
            ?deductible_cents: Integer?,
            ?out_of_pocket_max_cents: Integer?,
            ?tier: VitableConnect::Models::plan_tier?
          ) -> void

          def to_hash: -> {
            id: String,
            carrier_plan_id: String,
            monthly_premium_cents: Integer,
            name: String,
            deductible_cents: Integer?,
            out_of_pocket_max_cents: Integer?,
            tier: VitableConnect::Models::plan_tier?
          }
        end
      end
    end
  end
end
