module VitablePartnerAPI
  module Resources
    class BenefitProducts
      attr_reader plan_years: VitablePartnerAPI::Resources::BenefitProducts::PlanYears

      def list: (
        ?limit: Integer,
        ?offset: Integer,
        ?request_options: VitablePartnerAPI::request_opts
      ) -> VitablePartnerAPI::Models::BenefitProductListResponse

      def generate_quote: (
        String id,
        employer_id: String,
        ?metadata: ::Hash[Symbol, top],
        ?request_options: VitablePartnerAPI::request_opts
      ) -> VitablePartnerAPI::Quote

      def initialize: (client: VitablePartnerAPI::Client) -> void
    end
  end
end
