module VitablePartnerAPI
  module Resources
    class Employers
      attr_reader employees: VitablePartnerAPI::Resources::Employers::Employees

      def create: (
        legal_name: String,
        name: String,
        ?active: bool,
        ?request_options: VitablePartnerAPI::request_opts
      ) -> VitablePartnerAPI::Employer

      def retrieve: (
        String id,
        ?request_options: VitablePartnerAPI::request_opts
      ) -> VitablePartnerAPI::Employer

      def update: (
        String id,
        ?active: bool,
        ?legal_name: String,
        ?name: String,
        ?request_options: VitablePartnerAPI::request_opts
      ) -> VitablePartnerAPI::Employer

      def list: (
        ?limit: Integer,
        ?offset: Integer,
        ?request_options: VitablePartnerAPI::request_opts
      ) -> VitablePartnerAPI::Models::EmployerListResponse

      def create_eligibility_policy: (
        String id,
        classification: VitablePartnerAPI::Models::CreateEligibilityPolicyRequest::classification,
        waiting_period: VitablePartnerAPI::Models::CreateEligibilityPolicyRequest::waiting_period,
        ?policy_to_replace_id: String,
        ?request_options: VitablePartnerAPI::request_opts
      ) -> VitablePartnerAPI::EligibilityPolicy

      def initialize: (client: VitablePartnerAPI::Client) -> void
    end
  end
end
