module VitablePartnerAPI
  module Resources
    class Employees
      attr_reader dependents: VitablePartnerAPI::Resources::Employees::Dependents

      attr_reader qualifying_life_events: VitablePartnerAPI::Resources::Employees::QualifyingLifeEvents

      attr_reader enrollments: VitablePartnerAPI::Resources::Employees::Enrollments

      def retrieve: (
        String id,
        ?request_options: VitablePartnerAPI::request_opts
      ) -> VitablePartnerAPI::Employee

      def update: (
        String id,
        ?date_of_birth: Date,
        ?first_name: String,
        ?gender: VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::gender,
        ?last_name: String,
        ?sex: VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::sex,
        ?start_date: Date,
        ?suffix: String,
        ?request_options: VitablePartnerAPI::request_opts
      ) -> VitablePartnerAPI::Employee

      def terminate: (
        String id,
        ?request_options: VitablePartnerAPI::request_opts
      ) -> nil

      def initialize: (client: VitablePartnerAPI::Client) -> void
    end
  end
end
