module VitablePartnerAPI
  module Resources
    class Enrollments
      def get_eligible_plans: (
        String id,
        ?request_options: VitablePartnerAPI::request_opts
      ) -> VitablePartnerAPI::Models::EnrollmentGetEligiblePlansResponse

      def reissue: (
        String id,
        qualifying_life_event_id: String,
        ?request_options: VitablePartnerAPI::request_opts
      ) -> VitablePartnerAPI::Enrollment

      def initialize: (client: VitablePartnerAPI::Client) -> void
    end
  end
end
