module VitablePartnerAPI
  module Resources
    class PlanYears
      def update: (
        String id,
        ?contribution_classes: ::Array[VitablePartnerAPI::UpdatePlanYearRequest::ContributionClass],
        ?coverage_end_date: Date,
        ?coverage_start_date: Date,
        ?open_enrollment_end_date: Date,
        ?open_enrollment_start_date: Date,
        ?plan_costs: ::Array[VitablePartnerAPI::UpdatePlanYearRequest::PlanCost],
        ?request_options: VitablePartnerAPI::request_opts
      ) -> VitablePartnerAPI::PlanYear

      def initialize: (client: VitablePartnerAPI::Client) -> void
    end
  end
end
