module VitablePartnerAPI
  module Resources
    class Employers
      class Employees
        def create: (
          String id,
          date_of_birth: Date,
          first_name: String,
          last_name: String,
          start_date: Date,
          ?gender: VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::gender,
          ?sex: VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::sex,
          ?ssn: String,
          ?suffix: String,
          ?request_options: VitablePartnerAPI::request_opts
        ) -> VitablePartnerAPI::Employee

        def list: (
          String id,
          ?limit: Integer,
          ?offset: Integer,
          ?request_options: VitablePartnerAPI::request_opts
        ) -> VitablePartnerAPI::Models::Employers::EmployeeListResponse

        def initialize: (client: VitablePartnerAPI::Client) -> void
      end
    end
  end
end
