module VitablePartnerAPI
  module Models
    module BenefitProducts
      type create_plan_year_request =
        {
          coverage_end_date: Date,
          coverage_start_date: Date,
          employer_id: String,
          open_enrollment_end_date: Date,
          open_enrollment_start_date: Date,
          contribution_classes: ::Array[VitablePartnerAPI::BenefitProducts::CreatePlanYearRequest::ContributionClass],
          plan_costs: ::Array[VitablePartnerAPI::BenefitProducts::CreatePlanYearRequest::PlanCost]
        }

      class CreatePlanYearRequest < VitablePartnerAPI::Internal::Type::BaseModel
        attr_accessor coverage_end_date: Date

        attr_accessor coverage_start_date: Date

        attr_accessor employer_id: String

        attr_accessor open_enrollment_end_date: Date

        attr_accessor open_enrollment_start_date: Date

        attr_reader contribution_classes: ::Array[VitablePartnerAPI::BenefitProducts::CreatePlanYearRequest::ContributionClass]?

        def contribution_classes=: (
          ::Array[VitablePartnerAPI::BenefitProducts::CreatePlanYearRequest::ContributionClass]
        ) -> ::Array[VitablePartnerAPI::BenefitProducts::CreatePlanYearRequest::ContributionClass]

        attr_reader plan_costs: ::Array[VitablePartnerAPI::BenefitProducts::CreatePlanYearRequest::PlanCost]?

        def plan_costs=: (
          ::Array[VitablePartnerAPI::BenefitProducts::CreatePlanYearRequest::PlanCost]
        ) -> ::Array[VitablePartnerAPI::BenefitProducts::CreatePlanYearRequest::PlanCost]

        def initialize: (
          coverage_end_date: Date,
          coverage_start_date: Date,
          employer_id: String,
          open_enrollment_end_date: Date,
          open_enrollment_start_date: Date,
          ?contribution_classes: ::Array[VitablePartnerAPI::BenefitProducts::CreatePlanYearRequest::ContributionClass],
          ?plan_costs: ::Array[VitablePartnerAPI::BenefitProducts::CreatePlanYearRequest::PlanCost]
        ) -> void

        def to_hash: -> {
          coverage_end_date: Date,
          coverage_start_date: Date,
          employer_id: String,
          open_enrollment_end_date: Date,
          open_enrollment_start_date: Date,
          contribution_classes: ::Array[VitablePartnerAPI::BenefitProducts::CreatePlanYearRequest::ContributionClass],
          plan_costs: ::Array[VitablePartnerAPI::BenefitProducts::CreatePlanYearRequest::PlanCost]
        }

        type contribution_class =
          {
            compensation: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::compensation,
            employer_contribution_in_cents: Integer,
            employment: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::employment,
            family_status: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::family_status,
            location: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::location,
            location_value: String,
            max_age: Integer,
            min_age: Integer,
            plan_id: String?
          }

        class ContributionClass < VitablePartnerAPI::Internal::Type::BaseModel
          attr_accessor compensation: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::compensation

          attr_accessor employer_contribution_in_cents: Integer

          attr_accessor employment: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::employment

          attr_accessor family_status: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::family_status

          attr_accessor location: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::location

          attr_reader location_value: String?

          def location_value=: (String) -> String

          attr_reader max_age: Integer?

          def max_age=: (Integer) -> Integer

          attr_reader min_age: Integer?

          def min_age=: (Integer) -> Integer

          attr_accessor plan_id: String?

          def initialize: (
            compensation: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::compensation,
            employer_contribution_in_cents: Integer,
            employment: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::employment,
            family_status: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::family_status,
            location: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::location,
            ?location_value: String,
            ?max_age: Integer,
            ?min_age: Integer,
            ?plan_id: String?
          ) -> void

          def to_hash: -> {
            compensation: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::compensation,
            employer_contribution_in_cents: Integer,
            employment: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::employment,
            family_status: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::family_status,
            location: VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::location,
            location_value: String,
            max_age: Integer,
            min_age: Integer,
            plan_id: String?
          }

          type compensation = :UNSPECIFIED | :SALARY | :HOURLY

          module Compensation
            extend VitablePartnerAPI::Internal::Type::Enum

            UNSPECIFIED: :UNSPECIFIED
            SALARY: :SALARY
            HOURLY: :HOURLY

            def self?.values: -> ::Array[VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::compensation]
          end

          type employment =
            :UNSPECIFIED | :FULL_TIME | :PART_TIME | :TEMPORARY | :SEASONAL

          module Employment
            extend VitablePartnerAPI::Internal::Type::Enum

            UNSPECIFIED: :UNSPECIFIED
            FULL_TIME: :FULL_TIME
            PART_TIME: :PART_TIME
            TEMPORARY: :TEMPORARY
            SEASONAL: :SEASONAL

            def self?.values: -> ::Array[VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::employment]
          end

          type family_status = :UNSPECIFIED | :EE | :ES | :EC | :EF

          module FamilyStatus
            extend VitablePartnerAPI::Internal::Type::Enum

            UNSPECIFIED: :UNSPECIFIED
            EE: :EE
            ES: :ES
            EC: :EC
            EF: :EF

            def self?.values: -> ::Array[VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::family_status]
          end

          type location = :UNSPECIFIED | :STATE

          module Location
            extend VitablePartnerAPI::Internal::Type::Enum

            UNSPECIFIED: :UNSPECIFIED
            STATE: :STATE

            def self?.values: -> ::Array[VitablePartnerAPI::Models::BenefitProducts::CreatePlanYearRequest::ContributionClass::location]
          end
        end

        type plan_cost =
          {
            dependent_cost_in_cents: Integer,
            employee_cost_in_cents: Integer,
            plan_id: String
          }

        class PlanCost < VitablePartnerAPI::Internal::Type::BaseModel
          attr_accessor dependent_cost_in_cents: Integer

          attr_accessor employee_cost_in_cents: Integer

          attr_accessor plan_id: String

          def initialize: (
            dependent_cost_in_cents: Integer,
            employee_cost_in_cents: Integer,
            plan_id: String
          ) -> void

          def to_hash: -> {
            dependent_cost_in_cents: Integer,
            employee_cost_in_cents: Integer,
            plan_id: String
          }
        end
      end
    end
  end
end
