module VitablePartnerAPI
  module Models
    module BenefitProducts
      type plan_year_list_params =
        { employer_id: String }
        & VitablePartnerAPI::Internal::Type::request_parameters

      class PlanYearListParams < VitablePartnerAPI::Internal::Type::BaseModel
        extend VitablePartnerAPI::Internal::Type::RequestParameters::Converter
        include VitablePartnerAPI::Internal::Type::RequestParameters

        attr_accessor employer_id: String

        def initialize: (
          employer_id: String,
          ?request_options: VitablePartnerAPI::request_opts
        ) -> void

        def to_hash: -> {
          employer_id: String,
          request_options: VitablePartnerAPI::RequestOptions
        }
      end
    end
  end
end
