module VitableConnectAPI
  class Client < VitableConnectAPI::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    ENVIRONMENTS: {
      production: "https://api.vitablehealth.com",
      :environment_1 => "https://api.uat.vitablehealth.com"
    }

    attr_reader api_key: String

    attr_reader benefit_eligibility_policy: VitableConnectAPI::Resources::BenefitEligibilityPolicy

    attr_reader benefit_products: VitableConnectAPI::Resources::BenefitProducts

    attr_reader dependents: VitableConnectAPI::Resources::Dependents

    attr_reader employees: VitableConnectAPI::Resources::Employees

    attr_reader employers: VitableConnectAPI::Resources::Employers

    attr_reader enrollments: VitableConnectAPI::Resources::Enrollments

    attr_reader members: VitableConnectAPI::Resources::Members

    attr_reader plan_years: VitableConnectAPI::Resources::PlanYears

    attr_reader qualifying_life_events: VitableConnectAPI::Resources::QualifyingLifeEvents

    private def auth_headers: -> ::Hash[String, String]

    def initialize: (
      ?api_key: String?,
      ?environment: :production | :environment_1 | nil,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
