module VitablePartnerAPI
  module Resources
    class Employees
      class Dependents
        def create: (
          String id,
          date_of_birth: Date,
          first_name: String,
          last_name: String,
          relationship: VitablePartnerAPI::Models::CreateDependentRequest::relationship,
          ?gender: VitablePartnerAPI::Models::CreateDependentRequest::gender,
          ?sex: VitablePartnerAPI::Models::CreateDependentRequest::sex,
          ?suffix: String,
          ?request_options: VitablePartnerAPI::request_opts
        ) -> VitablePartnerAPI::Dependent

        def list: (
          String id,
          ?request_options: VitablePartnerAPI::request_opts
        ) -> VitablePartnerAPI::Models::Employees::DependentListResponse

        def initialize: (client: VitablePartnerAPI::Client) -> void
      end
    end
  end
end
