module VitablePartnerAPI
  module Resources
    class Employees
      class Enrollments
        def list: (
          String id,
          ?status: VitablePartnerAPI::Models::Employees::EnrollmentListParams::status,
          ?request_options: VitablePartnerAPI::request_opts
        ) -> VitablePartnerAPI::Models::Employees::EnrollmentListResponse

        def elect: (
          String id,
          elections: ::Array[VitablePartnerAPI::ElectBenefitsRequest::Election],
          ?request_options: VitablePartnerAPI::request_opts
        ) -> VitablePartnerAPI::Models::Employees::EnrollmentElectResponse

        def initialize: (client: VitablePartnerAPI::Client) -> void
      end
    end
  end
end
