module VitablePartnerAPI
  module Resources
    class Employees
      class QualifyingLifeEvents
        def create: (
          String id,
          event_date: Date,
          event_type: VitablePartnerAPI::Models::CreateQualifyingLifeEventRequest::event_type,
          ?description: String,
          ?proof_document_url: String,
          ?request_options: VitablePartnerAPI::request_opts
        ) -> VitablePartnerAPI::QualifyingLifeEvent

        def list: (
          String id,
          ?request_options: VitablePartnerAPI::request_opts
        ) -> VitablePartnerAPI::Models::Employees::QualifyingLifeEventListResponse

        def initialize: (client: VitablePartnerAPI::Client) -> void
      end
    end
  end
end
