module VitableConnectAPI
  module Models
    module Employees
      type enrollment_list_response =
        {
          data: ::Array[VitableConnectAPI::Enrollment],
          pagination: VitableConnectAPI::Models::Employees::EnrollmentListResponse::Pagination
        }

      class EnrollmentListResponse < VitableConnectAPI::Internal::Type::BaseModel
        attr_accessor data: ::Array[VitableConnectAPI::Enrollment]

        attr_accessor pagination: VitableConnectAPI::Models::Employees::EnrollmentListResponse::Pagination

        def initialize: (
          data: ::Array[VitableConnectAPI::Enrollment],
          pagination: VitableConnectAPI::Models::Employees::EnrollmentListResponse::Pagination
        ) -> void

        def to_hash: -> {
          data: ::Array[VitableConnectAPI::Enrollment],
          pagination: VitableConnectAPI::Models::Employees::EnrollmentListResponse::Pagination
        }

        type pagination =
          {
            limit: Integer,
            page: Integer,
            total: Integer,
            total_pages: Integer
          }

        class Pagination < VitableConnectAPI::Internal::Type::BaseModel
          attr_accessor limit: Integer

          attr_accessor page: Integer

          attr_accessor total: Integer

          attr_accessor total_pages: Integer

          def initialize: (
            limit: Integer,
            page: Integer,
            total: Integer,
            total_pages: Integer
          ) -> void

          def to_hash: -> {
            limit: Integer,
            page: Integer,
            total: Integer,
            total_pages: Integer
          }
        end
      end
    end
  end
end
