module VitableConnect
  class AuthIssueAccessTokenParams = VitableConnect::Models::AuthIssueAccessTokenParams

  class BenefitEligibilityPolicy = VitableConnect::Models::BenefitEligibilityPolicy

  class BenefitEligibilityPolicyRetrieveParams = VitableConnect::Models::BenefitEligibilityPolicyRetrieveParams

  module Category = VitableConnect::Models::Category

  class Employee = VitableConnect::Models::Employee

  module EmployeeClass = VitableConnect::Models::EmployeeClass

  class EmployeeResponse = VitableConnect::Models::EmployeeResponse

  class EmployeeRetrieveParams = VitableConnect::Models::EmployeeRetrieveParams

  module Employees = VitableConnect::Models::Employees

  class Employer = VitableConnect::Models::Employer

  class EmployerCreateEligibilityPolicyParams = VitableConnect::Models::EmployerCreateEligibilityPolicyParams

  class EmployerCreateParams = VitableConnect::Models::EmployerCreateParams

  class EmployerListParams = VitableConnect::Models::EmployerListParams

  class EmployerResponse = VitableConnect::Models::EmployerResponse

  class EmployerRetrieveParams = VitableConnect::Models::EmployerRetrieveParams

  module Employers = VitableConnect::Models::Employers

  class Enrollment = VitableConnect::Models::Enrollment

  class EnrollmentResponse = VitableConnect::Models::EnrollmentResponse

  class EnrollmentRetrieveParams = VitableConnect::Models::EnrollmentRetrieveParams

  module EnrollmentStatus = VitableConnect::Models::EnrollmentStatus

  class Pagination = VitableConnect::Models::Pagination

  module ProductCode = VitableConnect::Models::ProductCode

  module Type = VitableConnect::Models::Type
end
