module VitableConnect
  class AuthIssueAccessTokenParams = VitableConnect::Models::AuthIssueAccessTokenParams

  class BenefitEligibilityPolicy = VitableConnect::Models::BenefitEligibilityPolicy

  class BenefitEligibilityPolicyResponse = VitableConnect::Models::BenefitEligibilityPolicyResponse

  class BenefitEligibilityPolicyRetrieveParams = VitableConnect::Models::BenefitEligibilityPolicyRetrieveParams

  class Employee = VitableConnect::Models::Employee

  module EmployeeClass = VitableConnect::Models::EmployeeClass

  class EmployeeListEnrollmentsParams = VitableConnect::Models::EmployeeListEnrollmentsParams

  class EmployeeRetrieveParams = VitableConnect::Models::EmployeeRetrieveParams

  class Employer = VitableConnect::Models::Employer

  class EmployerCreateBenefitEligibilityPolicyParams = VitableConnect::Models::EmployerCreateBenefitEligibilityPolicyParams

  class EmployerCreateParams = VitableConnect::Models::EmployerCreateParams

  class EmployerListEmployeesParams = VitableConnect::Models::EmployerListEmployeesParams

  class EmployerListParams = VitableConnect::Models::EmployerListParams

  class EmployerResponse = VitableConnect::Models::EmployerResponse

  class EmployerRetrieveParams = VitableConnect::Models::EmployerRetrieveParams

  class EmployerSubmitCensusSyncParams = VitableConnect::Models::EmployerSubmitCensusSyncParams

  class Enrollment = VitableConnect::Models::Enrollment

  class EnrollmentRetrieveParams = VitableConnect::Models::EnrollmentRetrieveParams

  module EnrollmentStatus = VitableConnect::Models::EnrollmentStatus

  class Pagination = VitableConnect::Models::Pagination

  module Type = VitableConnect::Models::Type
end
