module VitableConnectAPI
  module Models
    type benefit_eligibility_policy_api =
      {
        id: String,
        active: bool,
        created_at: Time,
        effective_date: Date,
        employer_id: String,
        name: String,
        rules: ::Array[VitableConnectAPI::BenefitEligibilityPolicyAPI::Rule],
        updated_at: Time,
        description: String?,
        replaced_policy_id: String?
      }

    class BenefitEligibilityPolicyAPI < VitableConnectAPI::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor active: bool

      attr_accessor created_at: Time

      attr_accessor effective_date: Date

      attr_accessor employer_id: String

      attr_accessor name: String

      attr_accessor rules: ::Array[VitableConnectAPI::BenefitEligibilityPolicyAPI::Rule]

      attr_accessor updated_at: Time

      attr_accessor description: String?

      attr_accessor replaced_policy_id: String?

      def initialize: (
        id: String,
        active: bool,
        created_at: Time,
        effective_date: Date,
        employer_id: String,
        name: String,
        rules: ::Array[VitableConnectAPI::BenefitEligibilityPolicyAPI::Rule],
        updated_at: Time,
        ?description: String?,
        ?replaced_policy_id: String?
      ) -> void

      def to_hash: -> {
        id: String,
        active: bool,
        created_at: Time,
        effective_date: Date,
        employer_id: String,
        name: String,
        rules: ::Array[VitableConnectAPI::BenefitEligibilityPolicyAPI::Rule],
        updated_at: Time,
        description: String?,
        replaced_policy_id: String?
      }

      type rule = { operator: String, rule_type: String, value: top }

      class Rule < VitableConnectAPI::Internal::Type::BaseModel
        attr_accessor operator: String

        attr_accessor rule_type: String

        attr_accessor value: top

        def initialize: (
          operator: String,
          rule_type: String,
          value: top
        ) -> void

        def to_hash: -> { operator: String, rule_type: String, value: top }
      end
    end
  end
end
