module VitableConnectAPI
  module Models
    type benefit_product_list_response =
      {
        data: ::Array[VitableConnectAPI::Models::BenefitProductListResponse::Data],
        pagination: VitableConnectAPI::Models::BenefitProductListResponse::Pagination
      }

    class BenefitProductListResponse < VitableConnectAPI::Internal::Type::BaseModel
      attr_accessor data: ::Array[VitableConnectAPI::Models::BenefitProductListResponse::Data]

      attr_accessor pagination: VitableConnectAPI::Models::BenefitProductListResponse::Pagination

      def initialize: (
        data: ::Array[VitableConnectAPI::Models::BenefitProductListResponse::Data],
        pagination: VitableConnectAPI::Models::BenefitProductListResponse::Pagination
      ) -> void

      def to_hash: -> {
        data: ::Array[VitableConnectAPI::Models::BenefitProductListResponse::Data],
        pagination: VitableConnectAPI::Models::BenefitProductListResponse::Pagination
      }

      type data =
        {
          id: String,
          active_in: bool,
          category: VitableConnectAPI::Models::category,
          created_at: Time,
          name: String,
          product_code: VitableConnectAPI::Models::product_code,
          updated_at: Time,
          carrier_name: String?,
          description: String?
        }

      class Data < VitableConnectAPI::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor active_in: bool

        attr_accessor category: VitableConnectAPI::Models::category

        attr_accessor created_at: Time

        attr_accessor name: String

        attr_accessor product_code: VitableConnectAPI::Models::product_code

        attr_accessor updated_at: Time

        attr_accessor carrier_name: String?

        attr_accessor description: String?

        def initialize: (
          id: String,
          active_in: bool,
          category: VitableConnectAPI::Models::category,
          created_at: Time,
          name: String,
          product_code: VitableConnectAPI::Models::product_code,
          updated_at: Time,
          ?carrier_name: String?,
          ?description: String?
        ) -> void

        def to_hash: -> {
          id: String,
          active_in: bool,
          category: VitableConnectAPI::Models::category,
          created_at: Time,
          name: String,
          product_code: VitableConnectAPI::Models::product_code,
          updated_at: Time,
          carrier_name: String?,
          description: String?
        }
      end

      type pagination =
        { limit: Integer, page: Integer, total: Integer, total_pages: Integer }

      class Pagination < VitableConnectAPI::Internal::Type::BaseModel
        attr_accessor limit: Integer

        attr_accessor page: Integer

        attr_accessor total: Integer

        attr_accessor total_pages: Integer

        def initialize: (
          limit: Integer,
          page: Integer,
          total: Integer,
          total_pages: Integer
        ) -> void

        def to_hash: -> {
          limit: Integer,
          page: Integer,
          total: Integer,
          total_pages: Integer
        }
      end
    end
  end
end
