module VitableConnectAPI
  module Models
    type employer_update_response = { data: VitableConnectAPI::Employer }

    class EmployerUpdateResponse < VitableConnectAPI::Internal::Type::BaseModel
      attr_accessor data: VitableConnectAPI::Employer

      def initialize: (data: VitableConnectAPI::Employer) -> void

      def to_hash: -> { data: VitableConnectAPI::Employer }
    end
  end
end
