module VitableConnectAPI
  module Models
    type employer =
      {
        id: String,
        active: bool,
        created_at: Time,
        legal_name: String,
        name: String,
        organization_id: String,
        updated_at: Time,
        address: VitableConnectAPI::Employer::Address?,
        ein: String?,
        eligibility_policy_id: String?
      }

    class Employer < VitableConnectAPI::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor active: bool

      attr_accessor created_at: Time

      attr_accessor legal_name: String

      attr_accessor name: String

      attr_accessor organization_id: String

      attr_accessor updated_at: Time

      attr_accessor address: VitableConnectAPI::Employer::Address?

      attr_accessor ein: String?

      attr_accessor eligibility_policy_id: String?

      def initialize: (
        id: String,
        active: bool,
        created_at: Time,
        legal_name: String,
        name: String,
        organization_id: String,
        updated_at: Time,
        ?address: VitableConnectAPI::Employer::Address?,
        ?ein: String?,
        ?eligibility_policy_id: String?
      ) -> void

      def to_hash: -> {
        id: String,
        active: bool,
        created_at: Time,
        legal_name: String,
        name: String,
        organization_id: String,
        updated_at: Time,
        address: VitableConnectAPI::Employer::Address?,
        ein: String?,
        eligibility_policy_id: String?
      }

      type address =
        {
          city: String,
          state: String,
          :street_1 => String,
          zip_code: String,
          country: String,
          :street_2 => String?
        }

      class Address < VitableConnectAPI::Internal::Type::BaseModel
        attr_accessor city: String

        attr_accessor state: String

        attr_accessor street_1: String

        attr_accessor zip_code: String

        attr_reader country: String?

        def country=: (String) -> String

        attr_accessor street_2: String?

        def initialize: (
          city: String,
          state: String,
          street_1: String,
          zip_code: String,
          ?country: String,
          ?street_2: String?
        ) -> void

        def to_hash: -> {
          city: String,
          state: String,
          :street_1 => String,
          zip_code: String,
          country: String,
          :street_2 => String?
        }
      end
    end
  end
end
