module VitableConnectAPI
  module Models
    type employee_update_response = { data: VitableConnectAPI::Employee }

    class EmployeeUpdateResponse < VitableConnectAPI::Internal::Type::BaseModel
      attr_accessor data: VitableConnectAPI::Employee

      def initialize: (data: VitableConnectAPI::Employee) -> void

      def to_hash: -> { data: VitableConnectAPI::Employee }
    end
  end
end
