module VitableConnectAPI
  module Models
    type employer_create_params =
      {
        address: VitableConnectAPI::EmployerCreateParams::Address,
        ein: String,
        email: String,
        legal_name: String,
        name: String
      }
      & VitableConnectAPI::Internal::Type::request_parameters

    class EmployerCreateParams < VitableConnectAPI::Internal::Type::BaseModel
      extend VitableConnectAPI::Internal::Type::RequestParameters::Converter
      include VitableConnectAPI::Internal::Type::RequestParameters

      attr_accessor address: VitableConnectAPI::EmployerCreateParams::Address

      attr_accessor ein: String

      attr_accessor email: String

      attr_accessor legal_name: String

      attr_accessor name: String

      def initialize: (
        address: VitableConnectAPI::EmployerCreateParams::Address,
        ein: String,
        email: String,
        legal_name: String,
        name: String,
        ?request_options: VitableConnectAPI::request_opts
      ) -> void

      def to_hash: -> {
        address: VitableConnectAPI::EmployerCreateParams::Address,
        ein: String,
        email: String,
        legal_name: String,
        name: String,
        request_options: VitableConnectAPI::RequestOptions
      }

      type address =
        {
          :address_line_1 => String,
          city: String,
          state: String,
          zipcode: String,
          :address_line_2 => String?
        }

      class Address < VitableConnectAPI::Internal::Type::BaseModel
        attr_accessor address_line_1: String

        attr_accessor city: String

        attr_accessor state: String

        attr_accessor zipcode: String

        attr_accessor address_line_2: String?

        def initialize: (
          address_line_1: String,
          city: String,
          state: String,
          zipcode: String,
          ?address_line_2: String?
        ) -> void

        def to_hash: -> {
          :address_line_1 => String,
          city: String,
          state: String,
          zipcode: String,
          :address_line_2 => String?
        }
      end
    end
  end
end
