module VitableConnectAPI
  module Models
    type enrollment_reissue_response = { data: VitableConnectAPI::Enrollment }

    class EnrollmentReissueResponse < VitableConnectAPI::Internal::Type::BaseModel
      attr_accessor data: VitableConnectAPI::Enrollment

      def initialize: (data: VitableConnectAPI::Enrollment) -> void

      def to_hash: -> { data: VitableConnectAPI::Enrollment }
    end
  end
end
