module VitableConnectAPI
  module Models
    type enrollment_retrieve_response = { data: VitableConnectAPI::Enrollment }

    class EnrollmentRetrieveResponse < VitableConnectAPI::Internal::Type::BaseModel
      attr_accessor data: VitableConnectAPI::Enrollment

      def initialize: (data: VitableConnectAPI::Enrollment) -> void

      def to_hash: -> { data: VitableConnectAPI::Enrollment }
    end
  end
end
