module VitableConnectAPI
  module Models
    type plan_year_update_response =
      { data: VitableConnectAPI::BenefitProducts::PlanYear }

    class PlanYearUpdateResponse < VitableConnectAPI::Internal::Type::BaseModel
      attr_accessor data: VitableConnectAPI::BenefitProducts::PlanYear

      def initialize: (
        data: VitableConnectAPI::BenefitProducts::PlanYear
      ) -> void

      def to_hash: -> { data: VitableConnectAPI::BenefitProducts::PlanYear }
    end
  end
end
