module VitableConnectAPI
  module Models
    type plan_year_retrieve_params =
      {  } & VitableConnectAPI::Internal::Type::request_parameters

    class PlanYearRetrieveParams < VitableConnectAPI::Internal::Type::BaseModel
      extend VitableConnectAPI::Internal::Type::RequestParameters::Converter
      include VitableConnectAPI::Internal::Type::RequestParameters

      def initialize: (
        ?request_options: VitableConnectAPI::request_opts
      ) -> void

      def to_hash: -> { request_options: VitableConnectAPI::RequestOptions }
    end
  end
end
