module VitablePartnerAPI
  module Resources
    class BenefitProducts
      class PlanYears
        def create: (
          String id,
          coverage_end_date: Date,
          coverage_start_date: Date,
          employer_id: String,
          open_enrollment_end_date: Date,
          open_enrollment_start_date: Date,
          ?contribution_classes: ::Array[VitablePartnerAPI::BenefitProducts::CreatePlanYearRequest::ContributionClass],
          ?plan_costs: ::Array[VitablePartnerAPI::BenefitProducts::CreatePlanYearRequest::PlanCost],
          ?request_options: VitablePartnerAPI::request_opts
        ) -> VitablePartnerAPI::PlanYear

        def list: (
          String id,
          employer_id: String,
          ?request_options: VitablePartnerAPI::request_opts
        ) -> VitablePartnerAPI::Models::BenefitProducts::PlanYearListResponse

        def initialize: (client: VitablePartnerAPI::Client) -> void
      end
    end
  end
end
