module VitableConnect
  module Models
    module Employers
      type employee_list_response =
        {
          data: ::Array[VitableConnect::Employee],
          pagination: VitableConnect::Pagination
        }

      class EmployeeListResponse < VitableConnect::Internal::Type::BaseModel
        attr_accessor data: ::Array[VitableConnect::Employee]

        attr_accessor pagination: VitableConnect::Pagination

        def initialize: (
          data: ::Array[VitableConnect::Employee],
          pagination: VitableConnect::Pagination
        ) -> void

        def to_hash: -> {
          data: ::Array[VitableConnect::Employee],
          pagination: VitableConnect::Pagination
        }
      end
    end
  end
end
