# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "vitable_connect_api/version"
require_relative "vitable_connect_api/internal/util"
require_relative "vitable_connect_api/internal/type/converter"
require_relative "vitable_connect_api/internal/type/unknown"
require_relative "vitable_connect_api/internal/type/boolean"
require_relative "vitable_connect_api/internal/type/file_input"
require_relative "vitable_connect_api/internal/type/enum"
require_relative "vitable_connect_api/internal/type/union"
require_relative "vitable_connect_api/internal/type/array_of"
require_relative "vitable_connect_api/internal/type/hash_of"
require_relative "vitable_connect_api/internal/type/base_model"
require_relative "vitable_connect_api/internal/type/base_page"
require_relative "vitable_connect_api/internal/type/request_parameters"
require_relative "vitable_connect_api/internal"
require_relative "vitable_connect_api/request_options"
require_relative "vitable_connect_api/file_part"
require_relative "vitable_connect_api/errors"
require_relative "vitable_connect_api/internal/transport/base_client"
require_relative "vitable_connect_api/internal/transport/pooled_net_requester"
require_relative "vitable_connect_api/client"
require_relative "vitable_connect_api/models/benefit_eligibility_policy"
require_relative "vitable_connect_api/models/benefit_product_list_params"
require_relative "vitable_connect_api/models/benefit_product_list_response"
require_relative "vitable_connect_api/models/benefit_products/plan_year"
require_relative "vitable_connect_api/models/benefit_products/plan_year_create_params"
require_relative "vitable_connect_api/models/benefit_products/plan_year_create_response"
require_relative "vitable_connect_api/models/benefit_products/plan_year_list_params"
require_relative "vitable_connect_api/models/benefit_products/plan_year_list_response"
require_relative "vitable_connect_api/models/benefit_products/plan_year_status"
require_relative "vitable_connect_api/models/category"
require_relative "vitable_connect_api/models/coverage_tier"
require_relative "vitable_connect_api/models/dependent"
require_relative "vitable_connect_api/models/dependent_retrieve_params"
require_relative "vitable_connect_api/models/dependent_retrieve_response"
require_relative "vitable_connect_api/models/dependent_update_params"
require_relative "vitable_connect_api/models/dependent_update_response"
require_relative "vitable_connect_api/models/employee"
require_relative "vitable_connect_api/models/employee_retrieve_params"
require_relative "vitable_connect_api/models/employee_retrieve_response"
require_relative "vitable_connect_api/models/employees/enrollment_list_params"
require_relative "vitable_connect_api/models/employees/enrollment_list_response"
require_relative "vitable_connect_api/models/employees/enrollment_status"
require_relative "vitable_connect_api/models/employees/enrollment_submit_elections_params"
require_relative "vitable_connect_api/models/employees/enrollment_submit_elections_response"
require_relative "vitable_connect_api/models/employee_terminate_params"
require_relative "vitable_connect_api/models/employee_update_params"
require_relative "vitable_connect_api/models/employee_update_response"
require_relative "vitable_connect_api/models/employer"
require_relative "vitable_connect_api/models/employer_create_params"
require_relative "vitable_connect_api/models/employer_create_response"
require_relative "vitable_connect_api/models/employer_list_params"
require_relative "vitable_connect_api/models/employer_list_response"
require_relative "vitable_connect_api/models/employer_retrieve_params"
require_relative "vitable_connect_api/models/employer_retrieve_response"
require_relative "vitable_connect_api/models/employers/employee_class"
require_relative "vitable_connect_api/models/employers/employee_create_params"
require_relative "vitable_connect_api/models/employers/employee_create_response"
require_relative "vitable_connect_api/models/employers/employee_list_params"
require_relative "vitable_connect_api/models/employers/employee_list_response"
require_relative "vitable_connect_api/models/employer_update_params"
require_relative "vitable_connect_api/models/employer_update_response"
require_relative "vitable_connect_api/models/enrollment"
require_relative "vitable_connect_api/models/enrollment_list_plans_params"
require_relative "vitable_connect_api/models/enrollment_list_plans_response"
require_relative "vitable_connect_api/models/enrollment_reissue_params"
require_relative "vitable_connect_api/models/enrollment_reissue_response"
require_relative "vitable_connect_api/models/enrollment_retrieve_params"
require_relative "vitable_connect_api/models/enrollment_retrieve_response"
require_relative "vitable_connect_api/models/members/dependent_create_params"
require_relative "vitable_connect_api/models/members/dependent_create_response"
require_relative "vitable_connect_api/models/members/dependent_list_params"
require_relative "vitable_connect_api/models/members/dependent_list_response"
require_relative "vitable_connect_api/models/members/event_type"
require_relative "vitable_connect_api/models/members/qualifying_life_event"
require_relative "vitable_connect_api/models/members/qualifying_life_event_list_params"
require_relative "vitable_connect_api/models/members/qualifying_life_event_list_response"
require_relative "vitable_connect_api/models/members/qualifying_life_event_record_params"
require_relative "vitable_connect_api/models/members/qualifying_life_event_record_response"
require_relative "vitable_connect_api/models/members/qualifying_life_event_status"
require_relative "vitable_connect_api/models/members/relationship"
require_relative "vitable_connect_api/models/plan_tier"
require_relative "vitable_connect_api/models/plan_year_retrieve_params"
require_relative "vitable_connect_api/models/plan_year_retrieve_response"
require_relative "vitable_connect_api/models/plan_year_update_params"
require_relative "vitable_connect_api/models/plan_year_update_response"
require_relative "vitable_connect_api/models/product_code"
require_relative "vitable_connect_api/models/sex"
require_relative "vitable_connect_api/models"
require_relative "vitable_connect_api/resources/benefit_eligibility_policy"
require_relative "vitable_connect_api/resources/benefit_products"
require_relative "vitable_connect_api/resources/benefit_products/plan_years"
require_relative "vitable_connect_api/resources/dependents"
require_relative "vitable_connect_api/resources/employees"
require_relative "vitable_connect_api/resources/employees/enrollments"
require_relative "vitable_connect_api/resources/employers"
require_relative "vitable_connect_api/resources/employers/employees"
require_relative "vitable_connect_api/resources/enrollments"
require_relative "vitable_connect_api/resources/members"
require_relative "vitable_connect_api/resources/members/dependents"
require_relative "vitable_connect_api/resources/members/qualifying_life_events"
require_relative "vitable_connect_api/resources/plan_years"
require_relative "vitable_connect_api/resources/qualifying_life_events"
