# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "vitable_partner_api/version"
require_relative "vitable_partner_api/internal/util"
require_relative "vitable_partner_api/internal/type/converter"
require_relative "vitable_partner_api/internal/type/unknown"
require_relative "vitable_partner_api/internal/type/boolean"
require_relative "vitable_partner_api/internal/type/file_input"
require_relative "vitable_partner_api/internal/type/enum"
require_relative "vitable_partner_api/internal/type/union"
require_relative "vitable_partner_api/internal/type/array_of"
require_relative "vitable_partner_api/internal/type/hash_of"
require_relative "vitable_partner_api/internal/type/base_model"
require_relative "vitable_partner_api/internal/type/base_page"
require_relative "vitable_partner_api/internal/type/request_parameters"
require_relative "vitable_partner_api/internal"
require_relative "vitable_partner_api/request_options"
require_relative "vitable_partner_api/file_part"
require_relative "vitable_partner_api/errors"
require_relative "vitable_partner_api/internal/transport/base_client"
require_relative "vitable_partner_api/internal/transport/pooled_net_requester"
require_relative "vitable_partner_api/client"
require_relative "vitable_partner_api/models/quote_request"
require_relative "vitable_partner_api/models/benefit_products/create_plan_year_request"
require_relative "vitable_partner_api/models/member"
require_relative "vitable_partner_api/models/update_dependent_request"
require_relative "vitable_partner_api/models/create_dependent_request"
require_relative "vitable_partner_api/models/elect_benefits_request"
require_relative "vitable_partner_api/models/create_qualifying_life_event_request"
require_relative "vitable_partner_api/models/employers/update_employee_request"
require_relative "vitable_partner_api/models/create_eligibility_policy_request"
require_relative "vitable_partner_api/models/create_employer_request"
require_relative "vitable_partner_api/models/employers/create_employee_request"
require_relative "vitable_partner_api/models/update_employer_request"
require_relative "vitable_partner_api/models/reissue_enrollment_request"
require_relative "vitable_partner_api/models/update_plan_year_request"
require_relative "vitable_partner_api/models/benefit_product"
require_relative "vitable_partner_api/models/benefit_product_generate_quote_params"
require_relative "vitable_partner_api/models/benefit_product_list_params"
require_relative "vitable_partner_api/models/benefit_product_list_response"
require_relative "vitable_partner_api/models/benefit_products/plan_contribution_class"
require_relative "vitable_partner_api/models/benefit_products/plan_cost"
require_relative "vitable_partner_api/models/benefit_products/plan_year_create_params"
require_relative "vitable_partner_api/models/benefit_products/plan_year_list_params"
require_relative "vitable_partner_api/models/benefit_products/plan_year_list_response"
require_relative "vitable_partner_api/models/dependent"
require_relative "vitable_partner_api/models/dependent_update_params"
require_relative "vitable_partner_api/models/eligibility_policy"
require_relative "vitable_partner_api/models/employee"
require_relative "vitable_partner_api/models/employee_retrieve_params"
require_relative "vitable_partner_api/models/employees/dependent_create_params"
require_relative "vitable_partner_api/models/employees/dependent_list_params"
require_relative "vitable_partner_api/models/employees/dependent_list_response"
require_relative "vitable_partner_api/models/employees/enrollment_elect_params"
require_relative "vitable_partner_api/models/employees/enrollment_elect_response"
require_relative "vitable_partner_api/models/employees/enrollment_list_params"
require_relative "vitable_partner_api/models/employees/enrollment_list_response"
require_relative "vitable_partner_api/models/employees/qualifying_life_event_create_params"
require_relative "vitable_partner_api/models/employees/qualifying_life_event_list_params"
require_relative "vitable_partner_api/models/employees/qualifying_life_event_list_response"
require_relative "vitable_partner_api/models/employee_terminate_params"
require_relative "vitable_partner_api/models/employee_update_params"
require_relative "vitable_partner_api/models/employer"
require_relative "vitable_partner_api/models/employer_create_eligibility_policy_params"
require_relative "vitable_partner_api/models/employer_create_params"
require_relative "vitable_partner_api/models/employer_list_params"
require_relative "vitable_partner_api/models/employer_list_response"
require_relative "vitable_partner_api/models/employer_retrieve_params"
require_relative "vitable_partner_api/models/employers/employee_create_params"
require_relative "vitable_partner_api/models/employers/employee_list_params"
require_relative "vitable_partner_api/models/employers/employee_list_response"
require_relative "vitable_partner_api/models/employer_update_params"
require_relative "vitable_partner_api/models/enrollment"
require_relative "vitable_partner_api/models/enrollment_get_eligible_plans_params"
require_relative "vitable_partner_api/models/enrollment_get_eligible_plans_response"
require_relative "vitable_partner_api/models/enrollment_reissue_params"
require_relative "vitable_partner_api/models/plan"
require_relative "vitable_partner_api/models/plan_year"
require_relative "vitable_partner_api/models/plan_year_update_params"
require_relative "vitable_partner_api/models/qualifying_life_event"
require_relative "vitable_partner_api/models/quote"
require_relative "vitable_partner_api/models"
require_relative "vitable_partner_api/resources/benefit_products"
require_relative "vitable_partner_api/resources/benefit_products/plan_years"
require_relative "vitable_partner_api/resources/dependents"
require_relative "vitable_partner_api/resources/employees"
require_relative "vitable_partner_api/resources/employees/dependents"
require_relative "vitable_partner_api/resources/employees/enrollments"
require_relative "vitable_partner_api/resources/employees/qualifying_life_events"
require_relative "vitable_partner_api/resources/employers"
require_relative "vitable_partner_api/resources/employers/employees"
require_relative "vitable_partner_api/resources/enrollments"
require_relative "vitable_partner_api/resources/plan_years"
