module VitableConnect
  module Resources
    class Employees
      class Enrollments
        def list: (
          String employee_id,
          ?limit: Integer,
          ?page: Integer,
          ?request_options: VitableConnect::request_opts
        ) -> VitableConnect::Employees::EnrollmentList

        def initialize: (client: VitableConnect::Client) -> void
      end
    end
  end
end
