module VitableConnect
  module Models
    module Employees
      type enrollment_submit_elections_params =
        {
          employee_id: String,
          elections: ::Array[VitableConnect::Employees::EnrollmentSubmitElectionsParams::Election]
        }
        & VitableConnect::Internal::Type::request_parameters

      class EnrollmentSubmitElectionsParams < VitableConnect::Internal::Type::BaseModel
        extend VitableConnect::Internal::Type::RequestParameters::Converter
        include VitableConnect::Internal::Type::RequestParameters

        attr_accessor employee_id: String

        attr_accessor elections: ::Array[VitableConnect::Employees::EnrollmentSubmitElectionsParams::Election]

        def initialize: (
          employee_id: String,
          elections: ::Array[VitableConnect::Employees::EnrollmentSubmitElectionsParams::Election],
          ?request_options: VitableConnect::request_opts
        ) -> void

        def to_hash: -> {
          employee_id: String,
          elections: ::Array[VitableConnect::Employees::EnrollmentSubmitElectionsParams::Election],
          request_options: VitableConnect::RequestOptions
        }

        type election =
          {
            coverage_tier: VitableConnect::Models::coverage_tier,
            decision: VitableConnect::Models::Employees::EnrollmentSubmitElectionsParams::Election::decision,
            enrollment_id: String,
            dependent_ids: ::Array[String]?,
            selected_plan_id: String?
          }

        class Election < VitableConnect::Internal::Type::BaseModel
          attr_accessor coverage_tier: VitableConnect::Models::coverage_tier

          attr_accessor decision: VitableConnect::Models::Employees::EnrollmentSubmitElectionsParams::Election::decision

          attr_accessor enrollment_id: String

          attr_accessor dependent_ids: ::Array[String]?

          attr_accessor selected_plan_id: String?

          def initialize: (
            coverage_tier: VitableConnect::Models::coverage_tier,
            decision: VitableConnect::Models::Employees::EnrollmentSubmitElectionsParams::Election::decision,
            enrollment_id: String,
            ?dependent_ids: ::Array[String]?,
            ?selected_plan_id: String?
          ) -> void

          def to_hash: -> {
            coverage_tier: VitableConnect::Models::coverage_tier,
            decision: VitableConnect::Models::Employees::EnrollmentSubmitElectionsParams::Election::decision,
            enrollment_id: String,
            dependent_ids: ::Array[String]?,
            selected_plan_id: String?
          }

          type decision = :Enrolled | :Waived

          module Decision
            extend VitableConnect::Internal::Type::Enum

            ENROLLED: :Enrolled
            WAIVED: :Waived

            def self?.values: -> ::Array[VitableConnect::Models::Employees::EnrollmentSubmitElectionsParams::Election::decision]
          end
        end
      end
    end
  end
end
