module VitableConnect
  module Models
    module Employees
      type enrollment_list =
        {
          data: ::Array[VitableConnect::Enrollment],
          pagination: VitableConnect::Pagination
        }

      class EnrollmentList < VitableConnect::Internal::Type::BaseModel
        attr_accessor data: ::Array[VitableConnect::Enrollment]

        attr_accessor pagination: VitableConnect::Pagination

        def initialize: (
          data: ::Array[VitableConnect::Enrollment],
          pagination: VitableConnect::Pagination
        ) -> void

        def to_hash: -> {
          data: ::Array[VitableConnect::Enrollment],
          pagination: VitableConnect::Pagination
        }
      end
    end
  end
end
