module VitablePartnerAPI
  module Models
    module Employers
      type create_employee_request =
        {
          date_of_birth: Date,
          first_name: String,
          last_name: String,
          start_date: Date,
          gender: VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::gender,
          sex: VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::sex,
          ssn: String,
          suffix: String
        }

      class CreateEmployeeRequest < VitablePartnerAPI::Internal::Type::BaseModel
        attr_accessor date_of_birth: Date

        attr_accessor first_name: String

        attr_accessor last_name: String

        attr_accessor start_date: Date

        attr_reader gender: VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::gender?

        def gender=: (
          VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::gender
        ) -> VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::gender

        attr_reader sex: VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::sex?

        def sex=: (
          VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::sex
        ) -> VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::sex

        attr_reader ssn: String?

        def ssn=: (String) -> String

        attr_reader suffix: String?

        def suffix=: (String) -> String

        def initialize: (
          date_of_birth: Date,
          first_name: String,
          last_name: String,
          start_date: Date,
          ?gender: VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::gender,
          ?sex: VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::sex,
          ?ssn: String,
          ?suffix: String
        ) -> void

        def to_hash: -> {
          date_of_birth: Date,
          first_name: String,
          last_name: String,
          start_date: Date,
          gender: VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::gender,
          sex: VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::sex,
          ssn: String,
          suffix: String
        }

        type gender =
          :MALE | :FEMALE | :TRANSGENDER | :NON_BINARY | :PREFER_NOT_TO_RESPOND

        module Gender
          extend VitablePartnerAPI::Internal::Type::Enum

          MALE: :MALE
          FEMALE: :FEMALE
          TRANSGENDER: :TRANSGENDER
          NON_BINARY: :NON_BINARY
          PREFER_NOT_TO_RESPOND: :PREFER_NOT_TO_RESPOND

          def self?.values: -> ::Array[VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::gender]
        end

        type sex = :MALE | :FEMALE | :OTHER | :UNKNOWN

        module Sex
          extend VitablePartnerAPI::Internal::Type::Enum

          MALE: :MALE
          FEMALE: :FEMALE
          OTHER: :OTHER
          UNKNOWN: :UNKNOWN

          def self?.values: -> ::Array[VitablePartnerAPI::Models::Employers::CreateEmployeeRequest::sex]
        end
      end
    end
  end
end
