module VitablePartnerAPI
  module Models
    module Employers
      type update_employee_request =
        {
          date_of_birth: Date,
          first_name: String,
          gender: VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::gender,
          last_name: String,
          sex: VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::sex,
          start_date: Date,
          suffix: String
        }

      class UpdateEmployeeRequest < VitablePartnerAPI::Internal::Type::BaseModel
        attr_reader date_of_birth: Date?

        def date_of_birth=: (Date) -> Date

        attr_reader first_name: String?

        def first_name=: (String) -> String

        attr_reader gender: VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::gender?

        def gender=: (
          VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::gender
        ) -> VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::gender

        attr_reader last_name: String?

        def last_name=: (String) -> String

        attr_reader sex: VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::sex?

        def sex=: (
          VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::sex
        ) -> VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::sex

        attr_reader start_date: Date?

        def start_date=: (Date) -> Date

        attr_reader suffix: String?

        def suffix=: (String) -> String

        def initialize: (
          ?date_of_birth: Date,
          ?first_name: String,
          ?gender: VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::gender,
          ?last_name: String,
          ?sex: VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::sex,
          ?start_date: Date,
          ?suffix: String
        ) -> void

        def to_hash: -> {
          date_of_birth: Date,
          first_name: String,
          gender: VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::gender,
          last_name: String,
          sex: VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::sex,
          start_date: Date,
          suffix: String
        }

        type gender =
          :MALE | :FEMALE | :TRANSGENDER | :NON_BINARY | :PREFER_NOT_TO_RESPOND

        module Gender
          extend VitablePartnerAPI::Internal::Type::Enum

          MALE: :MALE
          FEMALE: :FEMALE
          TRANSGENDER: :TRANSGENDER
          NON_BINARY: :NON_BINARY
          PREFER_NOT_TO_RESPOND: :PREFER_NOT_TO_RESPOND

          def self?.values: -> ::Array[VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::gender]
        end

        type sex = :MALE | :FEMALE | :OTHER | :UNKNOWN

        module Sex
          extend VitablePartnerAPI::Internal::Type::Enum

          MALE: :MALE
          FEMALE: :FEMALE
          OTHER: :OTHER
          UNKNOWN: :UNKNOWN

          def self?.values: -> ::Array[VitablePartnerAPI::Models::Employers::UpdateEmployeeRequest::sex]
        end
      end
    end
  end
end
