# frozen_string_literal: true

module VitableConnect
  module Types
    module State
      extend VitableConnect::Internal::Types::Enum

      AL = "AL"
      AK = "AK"
      AZ = "AZ"
      AR = "AR"
      CA = "CA"
      CO = "CO"
      CT = "CT"
      DC = "DC"
      DE = "DE"
      FL = "FL"
      GA = "GA"
      HI = "HI"
      ID = "ID"
      IL = "IL"
      IN = "IN"
      IA = "IA"
      KS = "KS"
      KY = "KY"
      LA = "LA"
      ME = "ME"
      MD = "MD"
      MA = "MA"
      MI = "MI"
      MN = "MN"
      MS = "MS"
      MO = "MO"
      MT = "MT"
      NE = "NE"
      NV = "NV"
      NH = "NH"
      NJ = "NJ"
      NM = "NM"
      NY = "NY"
      NC = "NC"
      ND = "ND"
      OH = "OH"
      OK = "OK"
      OR = "OR"
      PA = "PA"
      RI = "RI"
      SC = "SC"
      SD = "SD"
      TN = "TN"
      TX = "TX"
      UT = "UT"
      VT = "VT"
      VA = "VA"
      WA = "WA"
      WI = "WI"
      WV = "WV"
      WY = "WY"
      PR = "PR"
      GU = "GU"
      AS = "AS"
      VI = "VI"
      MP = "MP"
      MH = "MH"
      PW = "PW"
      FM = "FM"
      AE = "AE"
      AA = "AA"
      AP = "AP"
    end
  end
end
