module VitableConnectAPI
  module Models
    module Members
      type dependent_list_params =
        {
          active_in: bool,
          limit: Integer,
          page: Integer,
          relationship: VitableConnectAPI::Models::Members::relationship
        }
        & VitableConnectAPI::Internal::Type::request_parameters

      class DependentListParams < VitableConnectAPI::Internal::Type::BaseModel
        extend VitableConnectAPI::Internal::Type::RequestParameters::Converter
        include VitableConnectAPI::Internal::Type::RequestParameters

        attr_reader active_in: bool?

        def active_in=: (bool) -> bool

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader page: Integer?

        def page=: (Integer) -> Integer

        attr_reader relationship: VitableConnectAPI::Models::Members::relationship?

        def relationship=: (
          VitableConnectAPI::Models::Members::relationship
        ) -> VitableConnectAPI::Models::Members::relationship

        def initialize: (
          ?active_in: bool,
          ?limit: Integer,
          ?page: Integer,
          ?relationship: VitableConnectAPI::Models::Members::relationship,
          ?request_options: VitableConnectAPI::request_opts
        ) -> void

        def to_hash: -> {
          active_in: bool,
          limit: Integer,
          page: Integer,
          relationship: VitableConnectAPI::Models::Members::relationship,
          request_options: VitableConnectAPI::RequestOptions
        }
      end
    end
  end
end
