module VitableConnectAPI
  module Models
    module Members
      type qualifying_life_event_status = :pending | :approved | :denied

      module QualifyingLifeEventStatus
        extend VitableConnectAPI::Internal::Type::Enum

        PENDING: :pending
        APPROVED: :approved
        DENIED: :denied

        def self?.values: -> ::Array[VitableConnectAPI::Models::Members::qualifying_life_event_status]
      end
    end
  end
end
