module VitableConnectAPI
  module Models
    module Members
      type qualifying_life_event_record_response =
        { data: VitableConnectAPI::Members::QualifyingLifeEvent }

      class QualifyingLifeEventRecordResponse < VitableConnectAPI::Internal::Type::BaseModel
        attr_accessor data: VitableConnectAPI::Members::QualifyingLifeEvent

        def initialize: (
          data: VitableConnectAPI::Members::QualifyingLifeEvent
        ) -> void

        def to_hash: -> {
          data: VitableConnectAPI::Members::QualifyingLifeEvent
        }
      end
    end
  end
end
