module VitableConnectAPI
  module Resources
    class BenefitProducts
      attr_reader plan_years: VitableConnectAPI::Resources::BenefitProducts::PlanYears

      def list: (
        ?active_in: bool,
        ?category: VitableConnectAPI::Models::category,
        ?limit: Integer,
        ?page: Integer,
        ?product_code: VitableConnectAPI::Models::product_code,
        ?request_options: VitableConnectAPI::request_opts
      ) -> VitableConnectAPI::Models::BenefitProductListResponse

      def initialize: (client: VitableConnectAPI::Client) -> void
    end
  end
end
