module VitableConnectAPI
  module Resources
    class Employers
      attr_reader employees: VitableConnectAPI::Resources::Employers::Employees

      def create: (
        address: VitableConnectAPI::EmployerCreateParams::Address,
        ein: String,
        email: String,
        legal_name: String,
        name: String,
        ?request_options: VitableConnectAPI::request_opts
      ) -> VitableConnectAPI::Models::EmployerCreateResponse

      def retrieve: (
        String employer_id,
        ?request_options: VitableConnectAPI::request_opts
      ) -> VitableConnectAPI::Models::EmployerRetrieveResponse

      def update: (
        String employer_id,
        ?active: bool?,
        ?address: VitableConnectAPI::EmployerUpdateParams::Address?,
        ?legal_name: String?,
        ?name: String?,
        ?request_options: VitableConnectAPI::request_opts
      ) -> VitableConnectAPI::Models::EmployerUpdateResponse

      def list: (
        ?active_in: bool,
        ?limit: Integer,
        ?name: String,
        ?page: Integer,
        ?request_options: VitableConnectAPI::request_opts
      ) -> VitableConnectAPI::Models::EmployerListResponse

      def initialize: (client: VitableConnectAPI::Client) -> void
    end
  end
end
