module VitableConnectAPI
  module Resources
    class Enrollments
      def retrieve: (
        String enrollment_id,
        ?request_options: VitableConnectAPI::request_opts
      ) -> VitableConnectAPI::Models::EnrollmentRetrieveResponse

      def list_plans: (
        String enrollment_id,
        ?request_options: VitableConnectAPI::request_opts
      ) -> VitableConnectAPI::Models::EnrollmentListPlansResponse

      def reissue: (
        String enrollment_id,
        qle_id: String,
        ?reason: String?,
        ?request_options: VitableConnectAPI::request_opts
      ) -> VitableConnectAPI::Models::EnrollmentReissueResponse

      def initialize: (client: VitableConnectAPI::Client) -> void
    end
  end
end
