module VitableConnectAPI
  module Resources
    class PlanYears
      def retrieve: (
        String plan_year_id,
        ?request_options: VitableConnectAPI::request_opts
      ) -> VitableConnectAPI::Models::PlanYearRetrieveResponse

      def update: (
        String plan_year_id,
        ?contribution_classes: ::Array[VitableConnectAPI::PlanYearUpdateParams::ContributionClass]?,
        ?open_enrollment_end: Date?,
        ?open_enrollment_start: Date?,
        ?status: String?,
        ?request_options: VitableConnectAPI::request_opts
      ) -> VitableConnectAPI::Models::PlanYearUpdateResponse

      def initialize: (client: VitableConnectAPI::Client) -> void
    end
  end
end
