module VitableConnect
  module Resources
    class Auth
      def issue_access_token: (
        grant_type: VitableConnect::Models::AuthIssueAccessTokenParams::grant_type,
        ?bound_entity: VitableConnect::AuthIssueAccessTokenParams::BoundEntity?,
        ?request_options: VitableConnect::request_opts
      ) -> VitableConnect::Models::AuthIssueAccessTokenResponse

      def initialize: (client: VitableConnect::Client) -> void
    end
  end
end
