module VitableConnect
  module Resources
    class Dependents
      def retrieve: (
        String dependent_id,
        ?request_options: VitableConnect::request_opts
      ) -> VitableConnect::DependentResponse

      def update: (
        String dependent_id,
        ?active: bool?,
        ?gender: String?,
        ?relationship: VitableConnect::Models::Members::relationship?,
        ?request_options: VitableConnect::request_opts
      ) -> VitableConnect::DependentResponse

      def initialize: (client: VitableConnect::Client) -> void
    end
  end
end
