module VitableConnect
  module Resources
    class Employers
      attr_reader employees: VitableConnect::Resources::Employers::Employees

      def create: (
        address: VitableConnect::EmployerCreateParams::Address,
        ein: String,
        email: String,
        legal_name: String,
        name: String,
        ?request_options: VitableConnect::request_opts
      ) -> VitableConnect::EmployerResponse

      def retrieve: (
        String employer_id,
        ?request_options: VitableConnect::request_opts
      ) -> VitableConnect::EmployerResponse

      def list: (
        ?limit: Integer,
        ?page: Integer,
        ?request_options: VitableConnect::request_opts
      ) -> VitableConnect::Models::EmployerListResponse

      def create_eligibility_policy: (
        String employer_id,
        classification: String,
        waiting_period: String,
        ?request_options: VitableConnect::request_opts
      ) -> VitableConnect::BenefitEligibilityPolicy

      def initialize: (client: VitableConnect::Client) -> void
    end
  end
end
