module VitableConnect
  module Resources
    class Employees
      attr_reader enrollments: VitableConnect::Resources::Employees::Enrollments

      def retrieve: (
        String employee_id,
        ?request_options: VitableConnect::request_opts
      ) -> VitableConnect::EmployeeResponse

      def initialize: (client: VitableConnect::Client) -> void
    end
  end
end
