module VitableConnect
  module Resources
    class Enrollments
      def retrieve: (
        String enrollment_id,
        ?request_options: VitableConnect::request_opts
      ) -> VitableConnect::EnrollmentResponse

      def initialize: (client: VitableConnect::Client) -> void
    end
  end
end
