module VitableConnect
  module Models
    module Members
      type dependent_list_response =
        {
          data: ::Array[VitableConnect::Dependent],
          pagination: VitableConnect::Pagination
        }

      class DependentListResponse < VitableConnect::Internal::Type::BaseModel
        attr_accessor data: ::Array[VitableConnect::Dependent]

        attr_accessor pagination: VitableConnect::Pagination

        def initialize: (
          data: ::Array[VitableConnect::Dependent],
          pagination: VitableConnect::Pagination
        ) -> void

        def to_hash: -> {
          data: ::Array[VitableConnect::Dependent],
          pagination: VitableConnect::Pagination
        }
      end
    end
  end
end
