module VitableConnect
  module Models
    module Members
      type dependent_create_params =
        {
          member_id: String,
          date_of_birth: Date,
          first_name: String,
          last_name: String,
          relationship: VitableConnect::Models::Members::relationship,
          sex: VitableConnect::Models::Employers::sex,
          gender: String?,
          ssn: String?,
          suffix: String?
        }
        & VitableConnect::Internal::Type::request_parameters

      class DependentCreateParams < VitableConnect::Internal::Type::BaseModel
        extend VitableConnect::Internal::Type::RequestParameters::Converter
        include VitableConnect::Internal::Type::RequestParameters

        attr_accessor member_id: String

        attr_accessor date_of_birth: Date

        attr_accessor first_name: String

        attr_accessor last_name: String

        attr_accessor relationship: VitableConnect::Models::Members::relationship

        attr_accessor sex: VitableConnect::Models::Employers::sex

        attr_accessor gender: String?

        attr_accessor ssn: String?

        attr_accessor suffix: String?

        def initialize: (
          member_id: String,
          date_of_birth: Date,
          first_name: String,
          last_name: String,
          relationship: VitableConnect::Models::Members::relationship,
          sex: VitableConnect::Models::Employers::sex,
          ?gender: String?,
          ?ssn: String?,
          ?suffix: String?,
          ?request_options: VitableConnect::request_opts
        ) -> void

        def to_hash: -> {
          member_id: String,
          date_of_birth: Date,
          first_name: String,
          last_name: String,
          relationship: VitableConnect::Models::Members::relationship,
          sex: VitableConnect::Models::Employers::sex,
          gender: String?,
          ssn: String?,
          suffix: String?,
          request_options: VitableConnect::RequestOptions
        }
      end
    end
  end
end
