module VitableConnect
  module Models
    module Members
      type dependent_list_params =
        {
          member_id: String,
          active_in: bool,
          limit: Integer,
          page: Integer,
          relationship: VitableConnect::Models::Members::relationship
        }
        & VitableConnect::Internal::Type::request_parameters

      class DependentListParams < VitableConnect::Internal::Type::BaseModel
        extend VitableConnect::Internal::Type::RequestParameters::Converter
        include VitableConnect::Internal::Type::RequestParameters

        attr_accessor member_id: String

        attr_reader active_in: bool?

        def active_in=: (bool) -> bool

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader page: Integer?

        def page=: (Integer) -> Integer

        attr_reader relationship: VitableConnect::Models::Members::relationship?

        def relationship=: (
          VitableConnect::Models::Members::relationship
        ) -> VitableConnect::Models::Members::relationship

        def initialize: (
          member_id: String,
          ?active_in: bool,
          ?limit: Integer,
          ?page: Integer,
          ?relationship: VitableConnect::Models::Members::relationship,
          ?request_options: VitableConnect::request_opts
        ) -> void

        def to_hash: -> {
          member_id: String,
          active_in: bool,
          limit: Integer,
          page: Integer,
          relationship: VitableConnect::Models::Members::relationship,
          request_options: VitableConnect::RequestOptions
        }
      end
    end
  end
end
