module VitableConnect
  module Models
    module Members
      type qualifying_life_event_list_params =
        {
          member_id: String,
          event_type: VitableConnect::Models::Members::event_type,
          limit: Integer,
          page: Integer,
          status: VitableConnect::Models::Members::qualifying_life_event_status
        }
        & VitableConnect::Internal::Type::request_parameters

      class QualifyingLifeEventListParams < VitableConnect::Internal::Type::BaseModel
        extend VitableConnect::Internal::Type::RequestParameters::Converter
        include VitableConnect::Internal::Type::RequestParameters

        attr_accessor member_id: String

        attr_reader event_type: VitableConnect::Models::Members::event_type?

        def event_type=: (
          VitableConnect::Models::Members::event_type
        ) -> VitableConnect::Models::Members::event_type

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader page: Integer?

        def page=: (Integer) -> Integer

        attr_reader status: VitableConnect::Models::Members::qualifying_life_event_status?

        def status=: (
          VitableConnect::Models::Members::qualifying_life_event_status
        ) -> VitableConnect::Models::Members::qualifying_life_event_status

        def initialize: (
          member_id: String,
          ?event_type: VitableConnect::Models::Members::event_type,
          ?limit: Integer,
          ?page: Integer,
          ?status: VitableConnect::Models::Members::qualifying_life_event_status,
          ?request_options: VitableConnect::request_opts
        ) -> void

        def to_hash: -> {
          member_id: String,
          event_type: VitableConnect::Models::Members::event_type,
          limit: Integer,
          page: Integer,
          status: VitableConnect::Models::Members::qualifying_life_event_status,
          request_options: VitableConnect::RequestOptions
        }
      end
    end
  end
end
