module VitableConnect
  module Models
    module Members
      type qualifying_life_event_list_response =
        {
          data: ::Array[VitableConnect::Members::QualifyingLifeEvent],
          pagination: VitableConnect::Pagination
        }

      class QualifyingLifeEventListResponse < VitableConnect::Internal::Type::BaseModel
        attr_accessor data: ::Array[VitableConnect::Members::QualifyingLifeEvent]

        attr_accessor pagination: VitableConnect::Pagination

        def initialize: (
          data: ::Array[VitableConnect::Members::QualifyingLifeEvent],
          pagination: VitableConnect::Pagination
        ) -> void

        def to_hash: -> {
          data: ::Array[VitableConnect::Members::QualifyingLifeEvent],
          pagination: VitableConnect::Pagination
        }
      end
    end
  end
end
