module VitableConnect
  module Models
    module Members
      type qualifying_life_event =
        {
          id: String,
          created_at: Time,
          employee_id: String,
          enrollment_window_end: Time,
          enrollment_window_start: Time,
          event_date: Date,
          event_type: String,
          member_id: String,
          status: VitableConnect::Models::Members::qualifying_life_event_status,
          updated_at: Time,
          notes: String?,
          reviewed_at: Time?,
          reviewed_by: String?
        }

      class QualifyingLifeEvent < VitableConnect::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor employee_id: String

        attr_accessor enrollment_window_end: Time

        attr_accessor enrollment_window_start: Time

        attr_accessor event_date: Date

        attr_accessor event_type: String

        attr_accessor member_id: String

        attr_accessor status: VitableConnect::Models::Members::qualifying_life_event_status

        attr_accessor updated_at: Time

        attr_accessor notes: String?

        attr_accessor reviewed_at: Time?

        attr_accessor reviewed_by: String?

        def initialize: (
          id: String,
          created_at: Time,
          employee_id: String,
          enrollment_window_end: Time,
          enrollment_window_start: Time,
          event_date: Date,
          event_type: String,
          member_id: String,
          status: VitableConnect::Models::Members::qualifying_life_event_status,
          updated_at: Time,
          ?notes: String?,
          ?reviewed_at: Time?,
          ?reviewed_by: String?
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          employee_id: String,
          enrollment_window_end: Time,
          enrollment_window_start: Time,
          event_date: Date,
          event_type: String,
          member_id: String,
          status: VitableConnect::Models::Members::qualifying_life_event_status,
          updated_at: Time,
          notes: String?,
          reviewed_at: Time?,
          reviewed_by: String?
        }
      end
    end
  end
end
