module VitableConnect
  module Models
    module Members
      type qualifying_life_event_retrieve_params =
        { member_id: String, qle_id: String }
        & VitableConnect::Internal::Type::request_parameters

      class QualifyingLifeEventRetrieveParams < VitableConnect::Internal::Type::BaseModel
        extend VitableConnect::Internal::Type::RequestParameters::Converter
        include VitableConnect::Internal::Type::RequestParameters

        attr_accessor member_id: String

        attr_accessor qle_id: String

        def initialize: (
          member_id: String,
          qle_id: String,
          ?request_options: VitableConnect::request_opts
        ) -> void

        def to_hash: -> {
          member_id: String,
          qle_id: String,
          request_options: VitableConnect::RequestOptions
        }
      end
    end
  end
end
