module VitableConnect
  module Models
    module Members
      type qualifying_life_event_response =
        { data: VitableConnect::Members::QualifyingLifeEvent }

      class QualifyingLifeEventResponse < VitableConnect::Internal::Type::BaseModel
        attr_accessor data: VitableConnect::Members::QualifyingLifeEvent

        def initialize: (
          data: VitableConnect::Members::QualifyingLifeEvent
        ) -> void

        def to_hash: -> { data: VitableConnect::Members::QualifyingLifeEvent }
      end
    end
  end
end
