module VitableConnect
  module Models
    type auth_complete_profile_params =
      {
        first_name: String,
        last_name: String,
        phone: String,
        user_type: VitableConnect::Models::AuthCompleteProfileParams::user_type
      }
      & VitableConnect::Internal::Type::request_parameters

    class AuthCompleteProfileParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor first_name: String

      attr_accessor last_name: String

      attr_accessor phone: String

      attr_reader user_type: VitableConnect::Models::AuthCompleteProfileParams::user_type?

      def user_type=: (
        VitableConnect::Models::AuthCompleteProfileParams::user_type
      ) -> VitableConnect::Models::AuthCompleteProfileParams::user_type

      def initialize: (
        first_name: String,
        last_name: String,
        phone: String,
        ?user_type: VitableConnect::Models::AuthCompleteProfileParams::user_type,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        first_name: String,
        last_name: String,
        phone: String,
        user_type: VitableConnect::Models::AuthCompleteProfileParams::user_type,
        request_options: VitableConnect::RequestOptions
      }

      type user_type =
        :Member
        | :NursePractitioner
        | :CompanyAdmin
        | :VitableAdmin
        | :ClinicalAdmin
        | :PartnerEmployee
        | :OrganizationUser
        | :ExternalAdmin

      module UserType
        extend VitableConnect::Internal::Type::Enum

        MEMBER: :Member
        NURSE_PRACTITIONER: :NursePractitioner
        COMPANY_ADMIN: :CompanyAdmin
        VITABLE_ADMIN: :VitableAdmin
        CLINICAL_ADMIN: :ClinicalAdmin
        PARTNER_EMPLOYEE: :PartnerEmployee
        ORGANIZATION_USER: :OrganizationUser
        EXTERNAL_ADMIN: :ExternalAdmin

        def self?.values: -> ::Array[VitableConnect::Models::AuthCompleteProfileParams::user_type]
      end
    end
  end
end
