module VitableConnect
  module Models
    type auth_retrieve_me_response =
      { user: VitableConnect::Models::AuthRetrieveMeResponse::User }

    class AuthRetrieveMeResponse < VitableConnect::Internal::Type::BaseModel
      attr_accessor user: VitableConnect::Models::AuthRetrieveMeResponse::User

      def initialize: (
        user: VitableConnect::Models::AuthRetrieveMeResponse::User
      ) -> void

      def to_hash: -> {
        user: VitableConnect::Models::AuthRetrieveMeResponse::User
      }

      type user =
        {
          email: String,
          first_name: String?,
          idp_provider: String,
          idp_user_id: String,
          last_name: String?
        }

      class User < VitableConnect::Internal::Type::BaseModel
        attr_accessor email: String

        attr_accessor first_name: String?

        attr_accessor idp_provider: String

        attr_accessor idp_user_id: String

        attr_accessor last_name: String?

        def initialize: (
          email: String,
          first_name: String?,
          idp_provider: String,
          idp_user_id: String,
          last_name: String?
        ) -> void

        def to_hash: -> {
          email: String,
          first_name: String?,
          idp_provider: String,
          idp_user_id: String,
          last_name: String?
        }
      end
    end
  end
end
