module VitableConnect
  module Models
    type auth_sign_up_params =
      { user_type: VitableConnect::Models::AuthSignUpParams::user_type? }
      & VitableConnect::Internal::Type::request_parameters

    class AuthSignUpParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor user_type: VitableConnect::Models::AuthSignUpParams::user_type?

      def initialize: (
        ?user_type: VitableConnect::Models::AuthSignUpParams::user_type?,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        user_type: VitableConnect::Models::AuthSignUpParams::user_type?,
        request_options: VitableConnect::RequestOptions
      }

      type user_type =
        :Member
        | :NursePractitioner
        | :CompanyAdmin
        | :VitableAdmin
        | :ClinicalAdmin
        | :PartnerEmployee
        | :OrganizationUser
        | :ExternalAdmin

      module UserType
        extend VitableConnect::Internal::Type::Enum

        MEMBER: :Member
        NURSE_PRACTITIONER: :NursePractitioner
        COMPANY_ADMIN: :CompanyAdmin
        VITABLE_ADMIN: :VitableAdmin
        CLINICAL_ADMIN: :ClinicalAdmin
        PARTNER_EMPLOYEE: :PartnerEmployee
        ORGANIZATION_USER: :OrganizationUser
        EXTERNAL_ADMIN: :ExternalAdmin

        def self?.values: -> ::Array[VitableConnect::Models::AuthSignUpParams::user_type]
      end
    end
  end
end
