module VitableConnect
  module Models
    type benefit_eligibility_policy_retrieve_params =
      { policy_id: String } & VitableConnect::Internal::Type::request_parameters

    class BenefitEligibilityPolicyRetrieveParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor policy_id: String

      def initialize: (
        policy_id: String,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        policy_id: String,
        request_options: VitableConnect::RequestOptions
      }
    end
  end
end
