module VitableConnect
  module Models
    type dependent_response = { data: VitableConnect::Dependent }

    class DependentResponse < VitableConnect::Internal::Type::BaseModel
      attr_accessor data: VitableConnect::Dependent

      def initialize: (data: VitableConnect::Dependent) -> void

      def to_hash: -> { data: VitableConnect::Dependent }
    end
  end
end
