module VitableConnect
  module Models
    type dependent_update_params =
      {
        active: bool?,
        gender: String?,
        relationship: VitableConnect::Models::Members::relationship?
      }
      & VitableConnect::Internal::Type::request_parameters

    class DependentUpdateParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor active: bool?

      attr_accessor gender: String?

      attr_accessor relationship: VitableConnect::Models::Members::relationship?

      def initialize: (
        ?active: bool?,
        ?gender: String?,
        ?relationship: VitableConnect::Models::Members::relationship?,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        active: bool?,
        gender: String?,
        relationship: VitableConnect::Models::Members::relationship?,
        request_options: VitableConnect::RequestOptions
      }
    end
  end
end
