module VitableConnect
  module Models
    type dependent_retrieve_params =
      { dependent_id: String }
      & VitableConnect::Internal::Type::request_parameters

    class DependentRetrieveParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor dependent_id: String

      def initialize: (
        dependent_id: String,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        dependent_id: String,
        request_options: VitableConnect::RequestOptions
      }
    end
  end
end
