module VitableConnect
  module Models
    type employee_terminate_params =
      { employee_id: String }
      & VitableConnect::Internal::Type::request_parameters

    class EmployeeTerminateParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor employee_id: String

      def initialize: (
        employee_id: String,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        employee_id: String,
        request_options: VitableConnect::RequestOptions
      }
    end
  end
end
