module VitableConnect
  module Models
    type employer_submit_payroll_access_setup_params =
      {
        employer_id: String,
        access_method: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::access_method,
        all_benefit_eligible_employees_present: bool,
        classifications_accurate: bool,
        employees_in_payroll_acknowledged: bool,
        has_additional_payroll_system: bool,
        is_controlled_group: bool,
        payroll_data_impacts_eligibility_acknowledged: bool,
        additional_access_method: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::additional_access_method?,
        additional_integration_confirmed: bool?,
        additional_login_url: String?,
        additional_password: String?,
        additional_phone: String?,
        additional_username: String?,
        classification_correction_source: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::classification_correction_source?,
        integration_confirmed: bool?,
        login_url: String?,
        misclassified_employee_names: ::Array[String],
        missing_employee_resolution: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::missing_employee_resolution?,
        password: String?,
        phone: String?,
        remaining_employee_action: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::remaining_employee_action?,
        same_payroll_covers_other_eins: bool?,
        username: String?
      }
      & VitableConnect::Internal::Type::request_parameters

    class EmployerSubmitPayrollAccessSetupParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor employer_id: String

      attr_accessor access_method: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::access_method

      attr_accessor all_benefit_eligible_employees_present: bool

      attr_accessor classifications_accurate: bool

      attr_accessor employees_in_payroll_acknowledged: bool

      attr_accessor has_additional_payroll_system: bool

      attr_accessor is_controlled_group: bool

      attr_accessor payroll_data_impacts_eligibility_acknowledged: bool

      attr_accessor additional_access_method: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::additional_access_method?

      attr_accessor additional_integration_confirmed: bool?

      attr_accessor additional_login_url: String?

      attr_accessor additional_password: String?

      attr_accessor additional_phone: String?

      attr_accessor additional_username: String?

      attr_accessor classification_correction_source: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::classification_correction_source?

      attr_accessor integration_confirmed: bool?

      attr_accessor login_url: String?

      attr_reader misclassified_employee_names: ::Array[String]?

      def misclassified_employee_names=: (::Array[String]) -> ::Array[String]

      attr_accessor missing_employee_resolution: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::missing_employee_resolution?

      attr_accessor password: String?

      attr_accessor phone: String?

      attr_accessor remaining_employee_action: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::remaining_employee_action?

      attr_accessor same_payroll_covers_other_eins: bool?

      attr_accessor username: String?

      def initialize: (
        employer_id: String,
        access_method: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::access_method,
        all_benefit_eligible_employees_present: bool,
        classifications_accurate: bool,
        employees_in_payroll_acknowledged: bool,
        has_additional_payroll_system: bool,
        is_controlled_group: bool,
        payroll_data_impacts_eligibility_acknowledged: bool,
        ?additional_access_method: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::additional_access_method?,
        ?additional_integration_confirmed: bool?,
        ?additional_login_url: String?,
        ?additional_password: String?,
        ?additional_phone: String?,
        ?additional_username: String?,
        ?classification_correction_source: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::classification_correction_source?,
        ?integration_confirmed: bool?,
        ?login_url: String?,
        ?misclassified_employee_names: ::Array[String],
        ?missing_employee_resolution: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::missing_employee_resolution?,
        ?password: String?,
        ?phone: String?,
        ?remaining_employee_action: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::remaining_employee_action?,
        ?same_payroll_covers_other_eins: bool?,
        ?username: String?,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        employer_id: String,
        access_method: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::access_method,
        all_benefit_eligible_employees_present: bool,
        classifications_accurate: bool,
        employees_in_payroll_acknowledged: bool,
        has_additional_payroll_system: bool,
        is_controlled_group: bool,
        payroll_data_impacts_eligibility_acknowledged: bool,
        additional_access_method: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::additional_access_method?,
        additional_integration_confirmed: bool?,
        additional_login_url: String?,
        additional_password: String?,
        additional_phone: String?,
        additional_username: String?,
        classification_correction_source: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::classification_correction_source?,
        integration_confirmed: bool?,
        login_url: String?,
        misclassified_employee_names: ::Array[String],
        missing_employee_resolution: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::missing_employee_resolution?,
        password: String?,
        phone: String?,
        remaining_employee_action: VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::remaining_employee_action?,
        same_payroll_covers_other_eins: bool?,
        username: String?,
        request_options: VitableConnect::RequestOptions
      }

      type access_method = :SELF_SETUP | :NEEDS_HELP

      module AccessMethod
        extend VitableConnect::Internal::Type::Enum

        SELF_SETUP: :SELF_SETUP
        NEEDS_HELP: :NEEDS_HELP

        def self?.values: -> ::Array[VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::access_method]
      end

      type additional_access_method = :SELF_SETUP | :NEEDS_HELP

      module AdditionalAccessMethod
        extend VitableConnect::Internal::Type::Enum

        SELF_SETUP: :SELF_SETUP
        NEEDS_HELP: :NEEDS_HELP

        def self?.values: -> ::Array[VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::additional_access_method]
      end

      type classification_correction_source = :ENTER_NAMES | :EMAIL_LIST

      module ClassificationCorrectionSource
        extend VitableConnect::Internal::Type::Enum

        ENTER_NAMES: :ENTER_NAMES
        EMAIL_LIST: :EMAIL_LIST

        def self?.values: -> ::Array[VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::classification_correction_source]
      end

      type missing_employee_resolution = :EMAIL_CENSUS | :SECOND_SYSTEM_ACCESS

      module MissingEmployeeResolution
        extend VitableConnect::Internal::Type::Enum

        EMAIL_CENSUS: :EMAIL_CENSUS
        SECOND_SYSTEM_ACCESS: :SECOND_SYSTEM_ACCESS

        def self?.values: -> ::Array[VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::missing_employee_resolution]
      end

      type remaining_employee_action = :VITABLE_UPDATE | :EMPLOYER_UPDATE

      module RemainingEmployeeAction
        extend VitableConnect::Internal::Type::Enum

        VITABLE_UPDATE: :VITABLE_UPDATE
        EMPLOYER_UPDATE: :EMPLOYER_UPDATE

        def self?.values: -> ::Array[VitableConnect::Models::EmployerSubmitPayrollAccessSetupParams::remaining_employee_action]
      end
    end
  end
end
