module VitableConnect
  module Models
    type employer_list_employees_params =
      {
        employer_id: String,
        employment_status: VitableConnect::Models::EmployerListEmployeesParams::employment_status,
        limit: Integer,
        page: Integer,
        search: String
      }
      & VitableConnect::Internal::Type::request_parameters

    class EmployerListEmployeesParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor employer_id: String

      attr_reader employment_status: VitableConnect::Models::EmployerListEmployeesParams::employment_status?

      def employment_status=: (
        VitableConnect::Models::EmployerListEmployeesParams::employment_status
      ) -> VitableConnect::Models::EmployerListEmployeesParams::employment_status

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader page: Integer?

      def page=: (Integer) -> Integer

      attr_reader search: String?

      def search=: (String) -> String

      def initialize: (
        employer_id: String,
        ?employment_status: VitableConnect::Models::EmployerListEmployeesParams::employment_status,
        ?limit: Integer,
        ?page: Integer,
        ?search: String,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        employer_id: String,
        employment_status: VitableConnect::Models::EmployerListEmployeesParams::employment_status,
        limit: Integer,
        page: Integer,
        search: String,
        request_options: VitableConnect::RequestOptions
      }

      type employment_status = :active | :terminated

      module EmploymentStatus
        extend VitableConnect::Internal::Type::Enum

        ACTIVE: :active
        TERMINATED: :terminated

        def self?.values: -> ::Array[VitableConnect::Models::EmployerListEmployeesParams::employment_status]
      end
    end
  end
end
