module VitableConnect
  module Models
    type employer_retrieve_benefit_plan_year_response =
      {
        data: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data
      }

    class EmployerRetrieveBenefitPlanYearResponse < VitableConnect::Internal::Type::BaseModel
      attr_accessor data: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data

      def initialize: (
        data: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data
      ) -> void

      def to_hash: -> {
        data: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data
      }

      type data =
        {
          benefit_id: String,
          benefit_plan_year_id: String,
          carrier: String?,
          contribution_strategy: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy,
          coverage_end: Date?,
          coverage_start: Date,
          eligibility_policy: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy?,
          employee_contribution: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EmployeeContribution?,
          employer_contribution: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EmployerContribution?,
          enrollment_rate: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EnrollmentRate,
          family: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::family,
          network_names: ::Array[String],
          offered_states: ::Array[String],
          open_enrollment_end: Date?,
          open_enrollment_start: Date,
          premium_in_cents: Integer?,
          product_name: String,
          spd_file_url: String?,
          status: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::status,
          year: Integer
        }

      class Data < VitableConnect::Internal::Type::BaseModel
        attr_accessor benefit_id: String

        attr_accessor benefit_plan_year_id: String

        attr_accessor carrier: String?

        attr_accessor contribution_strategy: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy

        attr_accessor coverage_end: Date?

        attr_accessor coverage_start: Date

        attr_accessor eligibility_policy: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy?

        attr_accessor employee_contribution: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EmployeeContribution?

        attr_accessor employer_contribution: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EmployerContribution?

        attr_accessor enrollment_rate: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EnrollmentRate

        attr_accessor family: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::family

        attr_accessor network_names: ::Array[String]

        attr_accessor offered_states: ::Array[String]

        attr_accessor open_enrollment_end: Date?

        attr_accessor open_enrollment_start: Date

        attr_accessor premium_in_cents: Integer?

        attr_accessor product_name: String

        attr_accessor spd_file_url: String?

        attr_accessor status: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::status

        attr_accessor year: Integer

        def initialize: (
          benefit_id: String,
          benefit_plan_year_id: String,
          carrier: String?,
          contribution_strategy: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy,
          coverage_end: Date?,
          coverage_start: Date,
          eligibility_policy: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy?,
          employee_contribution: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EmployeeContribution?,
          employer_contribution: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EmployerContribution?,
          enrollment_rate: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EnrollmentRate,
          family: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::family,
          network_names: ::Array[String],
          offered_states: ::Array[String],
          open_enrollment_end: Date?,
          open_enrollment_start: Date,
          premium_in_cents: Integer?,
          product_name: String,
          spd_file_url: String?,
          status: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::status,
          year: Integer
        ) -> void

        def to_hash: -> {
          benefit_id: String,
          benefit_plan_year_id: String,
          carrier: String?,
          contribution_strategy: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy,
          coverage_end: Date?,
          coverage_start: Date,
          eligibility_policy: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy?,
          employee_contribution: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EmployeeContribution?,
          employer_contribution: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EmployerContribution?,
          enrollment_rate: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EnrollmentRate,
          family: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::family,
          network_names: ::Array[String],
          offered_states: ::Array[String],
          open_enrollment_end: Date?,
          open_enrollment_start: Date,
          premium_in_cents: Integer?,
          product_name: String,
          spd_file_url: String?,
          status: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::status,
          year: Integer
        }

        type contribution_strategy =
          {
            contribution_tiers: ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::ContributionTier],
            ichra_contribution_classes: ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass]
          }

        class ContributionStrategy < VitableConnect::Internal::Type::BaseModel
          attr_accessor contribution_tiers: ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::ContributionTier]

          attr_accessor ichra_contribution_classes: ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass]

          def initialize: (
            contribution_tiers: ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::ContributionTier],
            ichra_contribution_classes: ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass]
          ) -> void

          def to_hash: -> {
            contribution_tiers: ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::ContributionTier],
            ichra_contribution_classes: ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass]
          }

          type contribution_tier =
            {
              benefit_plan_id: String,
              benefit_plan_name: String,
              benefit_plan_tier_name: String,
              cost: Integer,
              cost_per_dependent: Integer,
              dependents_required_in: bool,
              spouse_required_in: bool
            }

          class ContributionTier < VitableConnect::Internal::Type::BaseModel
            attr_accessor benefit_plan_id: String

            attr_accessor benefit_plan_name: String

            attr_accessor benefit_plan_tier_name: String

            attr_accessor cost: Integer

            attr_accessor cost_per_dependent: Integer

            attr_accessor dependents_required_in: bool

            attr_accessor spouse_required_in: bool

            def initialize: (
              benefit_plan_id: String,
              benefit_plan_name: String,
              benefit_plan_tier_name: String,
              cost: Integer,
              cost_per_dependent: Integer,
              dependents_required_in: bool,
              spouse_required_in: bool
            ) -> void

            def to_hash: -> {
              benefit_plan_id: String,
              benefit_plan_name: String,
              benefit_plan_tier_name: String,
              cost: Integer,
              cost_per_dependent: Integer,
              dependents_required_in: bool,
              spouse_required_in: bool
            }
          end

          type ichra_contribution_class =
            {
              amount_in_cents: Integer,
              compensation: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::compensation,
              contribution_class_id: String,
              employment: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::employment,
              family_status: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::family_status,
              location: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::location,
              location_value: String?,
              max_age: Integer?,
              min_age: Integer?
            }

          class IchraContributionClass < VitableConnect::Internal::Type::BaseModel
            attr_accessor amount_in_cents: Integer

            attr_accessor compensation: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::compensation

            attr_accessor contribution_class_id: String

            attr_accessor employment: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::employment

            attr_accessor family_status: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::family_status

            attr_accessor location: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::location

            attr_accessor location_value: String?

            attr_accessor max_age: Integer?

            attr_accessor min_age: Integer?

            def initialize: (
              amount_in_cents: Integer,
              compensation: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::compensation,
              contribution_class_id: String,
              employment: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::employment,
              family_status: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::family_status,
              location: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::location,
              location_value: String?,
              max_age: Integer?,
              min_age: Integer?
            ) -> void

            def to_hash: -> {
              amount_in_cents: Integer,
              compensation: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::compensation,
              contribution_class_id: String,
              employment: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::employment,
              family_status: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::family_status,
              location: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::location,
              location_value: String?,
              max_age: Integer?,
              min_age: Integer?
            }

            type compensation = :Unspecified | :Salary | :Hourly

            module Compensation
              extend VitableConnect::Internal::Type::Enum

              UNSPECIFIED: :Unspecified
              SALARY: :Salary
              HOURLY: :Hourly

              def self?.values: -> ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::compensation]
            end

            type employment =
              :Unspecified
              | :"Full Time"
              | :"Part Time"
              | :Temporary
              | :Seasonal

            module Employment
              extend VitableConnect::Internal::Type::Enum

              UNSPECIFIED: :Unspecified
              FULL_TIME: :"Full Time"
              PART_TIME: :"Part Time"
              TEMPORARY: :Temporary
              SEASONAL: :Seasonal

              def self?.values: -> ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::employment]
            end

            type family_status = :Unspecified | :EE | :ES | :EC | :EF

            module FamilyStatus
              extend VitableConnect::Internal::Type::Enum

              UNSPECIFIED: :Unspecified
              EE: :EE
              ES: :ES
              EC: :EC
              EF: :EF

              def self?.values: -> ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::family_status]
            end

            type location = :Unspecified | :State

            module Location
              extend VitableConnect::Internal::Type::Enum

              UNSPECIFIED: :Unspecified
              STATE: :State

              def self?.values: -> ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::ContributionStrategy::IchraContributionClass::location]
            end
          end
        end

        type eligibility_policy =
          {
            rules: ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule],
            termination_n_months: Integer?,
            termination_rule: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::termination_rule,
            waiting_period: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::waiting_period?
          }

        class EligibilityPolicy < VitableConnect::Internal::Type::BaseModel
          attr_accessor rules: ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule]

          attr_accessor termination_n_months: Integer?

          attr_accessor termination_rule: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::termination_rule

          attr_accessor waiting_period: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::waiting_period?

          def initialize: (
            rules: ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule],
            termination_n_months: Integer?,
            termination_rule: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::termination_rule,
            waiting_period: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::waiting_period?
          ) -> void

          def to_hash: -> {
            rules: ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule],
            termination_n_months: Integer?,
            termination_rule: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::termination_rule,
            waiting_period: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::waiting_period?
          }

          type rule =
            {
              compensation_type: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::compensation_type,
              eligible_geographical_location: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::EligibleGeographicalLocation,
              employee_class: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::employee_class
            }

          class Rule < VitableConnect::Internal::Type::BaseModel
            attr_accessor compensation_type: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::compensation_type

            attr_accessor eligible_geographical_location: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::EligibleGeographicalLocation

            attr_accessor employee_class: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::employee_class

            def initialize: (
              compensation_type: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::compensation_type,
              eligible_geographical_location: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::EligibleGeographicalLocation,
              employee_class: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::employee_class
            ) -> void

            def to_hash: -> {
              compensation_type: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::compensation_type,
              eligible_geographical_location: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::EligibleGeographicalLocation,
              employee_class: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::employee_class
            }

            type compensation_type = :Salary | :Hourly | :All

            module CompensationType
              extend VitableConnect::Internal::Type::Enum

              SALARY: :Salary
              HOURLY: :Hourly
              ALL: :All

              def self?.values: -> ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::compensation_type]
            end

            type eligible_geographical_location =
              {
                state_codes: ::Array[String],
                type: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::EligibleGeographicalLocation::type_
              }

            class EligibleGeographicalLocation < VitableConnect::Internal::Type::BaseModel
              attr_accessor state_codes: ::Array[String]

              attr_accessor type: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::EligibleGeographicalLocation::type_

              def initialize: (
                state_codes: ::Array[String],
                type: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::EligibleGeographicalLocation::type_
              ) -> void

              def to_hash: -> {
                state_codes: ::Array[String],
                type: VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::EligibleGeographicalLocation::type_
              }

              type type_ = :All | :StateCodes

              module Type
                extend VitableConnect::Internal::Type::Enum

                ALL: :All
                STATE_CODES: :StateCodes

                def self?.values: -> ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::EligibleGeographicalLocation::type_]
              end
            end

            type employee_class =
              :"Full Time"
              | :"Part Time"
              | :Temporary
              | :Intern
              | :Seasonal
              | :"Individual Contractor"
              | :All

            module EmployeeClass
              extend VitableConnect::Internal::Type::Enum

              FULL_TIME: :"Full Time"
              PART_TIME: :"Part Time"
              TEMPORARY: :Temporary
              INTERN: :Intern
              SEASONAL: :Seasonal
              INDIVIDUAL_CONTRACTOR: :"Individual Contractor"
              ALL: :All

              def self?.values: -> ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::Rule::employee_class]
            end
          end

          type termination_rule = :END_OF_N_MONTHS | :END_OF_PLAN_YEAR

          module TerminationRule
            extend VitableConnect::Internal::Type::Enum

            END_OF_N_MONTHS: :END_OF_N_MONTHS
            END_OF_PLAN_YEAR: :END_OF_PLAN_YEAR

            def self?.values: -> ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::termination_rule]
          end

          type waiting_period =
            :FIRST_OF_FOLLOWING_MONTH | :THIRTY_DAYS | :SIXTY_DAYS

          module WaitingPeriod
            extend VitableConnect::Internal::Type::Enum

            FIRST_OF_FOLLOWING_MONTH: :FIRST_OF_FOLLOWING_MONTH
            THIRTY_DAYS: :THIRTY_DAYS
            SIXTY_DAYS: :SIXTY_DAYS

            def self?.values: -> ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::EligibilityPolicy::waiting_period]
          end
        end

        type employee_contribution = { max_cents: Integer, min_cents: Integer }

        class EmployeeContribution < VitableConnect::Internal::Type::BaseModel
          attr_accessor max_cents: Integer

          attr_accessor min_cents: Integer

          def initialize: (max_cents: Integer, min_cents: Integer) -> void

          def to_hash: -> { max_cents: Integer, min_cents: Integer }
        end

        type employer_contribution = { max_cents: Integer, min_cents: Integer }

        class EmployerContribution < VitableConnect::Internal::Type::BaseModel
          attr_accessor max_cents: Integer

          attr_accessor min_cents: Integer

          def initialize: (max_cents: Integer, min_cents: Integer) -> void

          def to_hash: -> { max_cents: Integer, min_cents: Integer }
        end

        type enrollment_rate =
          { eligible: Integer, enrolled: Integer, percentage: Integer }

        class EnrollmentRate < VitableConnect::Internal::Type::BaseModel
          attr_accessor eligible: Integer

          attr_accessor enrolled: Integer

          attr_accessor percentage: Integer

          def initialize: (
            eligible: Integer,
            enrolled: Integer,
            percentage: Integer
          ) -> void

          def to_hash: -> {
            eligible: Integer,
            enrolled: Integer,
            percentage: Integer
          }
        end

        type family = :mec | :mvp | :ichra | :vpc | :dental | :vision

        module Family
          extend VitableConnect::Internal::Type::Enum

          MEC: :mec
          MVP: :mvp
          ICHRA: :ichra
          VPC: :vpc
          DENTAL: :dental
          VISION: :vision

          def self?.values: -> ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::family]
        end

        type status = :active | :upcoming | :open_enrollment | :inactive

        module Status
          extend VitableConnect::Internal::Type::Enum

          ACTIVE: :active
          UPCOMING: :upcoming
          OPEN_ENROLLMENT: :open_enrollment
          INACTIVE: :inactive

          def self?.values: -> ::Array[VitableConnect::Models::EmployerRetrieveBenefitPlanYearResponse::Data::status]
        end
      end
    end
  end
end
