module VitableConnect
  module Models
    type employer =
      {
        id: String,
        active: bool,
        address: VitableConnect::Employer::Address,
        created_at: Time,
        ein: String?,
        eligibility_policy_id: String?,
        legal_name: String,
        name: String,
        organization_id: String,
        updated_at: Time,
        email: String?
      }

    class Employer < VitableConnect::Internal::Type::BaseModel
      attr_accessor active: bool

      attr_accessor address: VitableConnect::Employer::Address

      attr_accessor created_at: Time

      attr_accessor legal_name: String

      attr_accessor name: String

      attr_accessor updated_at: Time

      attr_accessor email: String?

      attr_accessor id: String

      attr_accessor ein: String?

      attr_accessor eligibility_policy_id: String?

      attr_accessor organization_id: String

      def initialize: (
        id: String,
        active: bool,
        address: VitableConnect::Employer::Address,
        created_at: Time,
        ein: String?,
        eligibility_policy_id: String?,
        legal_name: String,
        name: String,
        organization_id: String,
        updated_at: Time,
        ?email: String?
      ) -> void

      def to_hash: -> {
        id: String,
        active: bool,
        address: VitableConnect::Employer::Address,
        created_at: Time,
        ein: String?,
        eligibility_policy_id: String?,
        legal_name: String,
        name: String,
        organization_id: String,
        updated_at: Time,
        email: String?
      }

      type address =
        {
          :address_line_1 => String,
          city: String,
          state: String,
          zipcode: String,
          :address_line_2 => String?
        }

      class Address < VitableConnect::Internal::Type::BaseModel
        attr_accessor address_line_1: String

        attr_accessor city: String

        attr_accessor state: String

        attr_accessor zipcode: String

        attr_accessor address_line_2: String?

        def initialize: (
          address_line_1: String,
          city: String,
          state: String,
          zipcode: String,
          ?address_line_2: String?
        ) -> void

        def to_hash: -> {
          :address_line_1 => String,
          city: String,
          state: String,
          zipcode: String,
          :address_line_2 => String?
        }
      end
    end
  end
end
