module VitableConnect
  module Models
    type employee_response = { data: VitableConnect::Employee }

    class EmployeeResponse < VitableConnect::Internal::Type::BaseModel
      attr_accessor data: VitableConnect::Employee

      def initialize: (data: VitableConnect::Employee) -> void

      def to_hash: -> { data: VitableConnect::Employee }
    end
  end
end
