module VitableConnect
  module Models
    type employer_submit_payroll_access_setup_response =
      {
        data: VitableConnect::Models::EmployerSubmitPayrollAccessSetupResponse::Data
      }

    class EmployerSubmitPayrollAccessSetupResponse < VitableConnect::Internal::Type::BaseModel
      attr_accessor data: VitableConnect::Models::EmployerSubmitPayrollAccessSetupResponse::Data

      def initialize: (
        data: VitableConnect::Models::EmployerSubmitPayrollAccessSetupResponse::Data
      ) -> void

      def to_hash: -> {
        data: VitableConnect::Models::EmployerSubmitPayrollAccessSetupResponse::Data
      }

      type data = { completed: bool, submitted_at: Time? }

      class Data < VitableConnect::Internal::Type::BaseModel
        attr_accessor completed: bool

        attr_accessor submitted_at: Time?

        def initialize: (completed: bool, submitted_at: Time?) -> void

        def to_hash: -> { completed: bool, submitted_at: Time? }
      end
    end
  end
end
