module VitableConnect
  module Models
    type employer_retrieve_invoice_pdf_response = { download_url: String }

    class EmployerRetrieveInvoicePdfResponse < VitableConnect::Internal::Type::BaseModel
      attr_accessor download_url: String

      def initialize: (download_url: String) -> void

      def to_hash: -> { download_url: String }
    end
  end
end
