module VitableConnect
  module Models
    type employer_list_invoices_response =
      {
        data: ::Array[VitableConnect::Models::EmployerListInvoicesResponse::Data],
        pagination: VitableConnect::Models::EmployerListInvoicesResponse::Pagination
      }

    class EmployerListInvoicesResponse < VitableConnect::Internal::Type::BaseModel
      attr_accessor data: ::Array[VitableConnect::Models::EmployerListInvoicesResponse::Data]

      attr_accessor pagination: VitableConnect::Models::EmployerListInvoicesResponse::Pagination

      def initialize: (
        data: ::Array[VitableConnect::Models::EmployerListInvoicesResponse::Data],
        pagination: VitableConnect::Models::EmployerListInvoicesResponse::Pagination
      ) -> void

      def to_hash: -> {
        data: ::Array[VitableConnect::Models::EmployerListInvoicesResponse::Data],
        pagination: VitableConnect::Models::EmployerListInvoicesResponse::Pagination
      }

      type data =
        { invoice_id: String, period: String?, status: String?, total: Float? }

      class Data < VitableConnect::Internal::Type::BaseModel
        attr_accessor invoice_id: String

        attr_accessor period: String?

        attr_accessor status: String?

        attr_accessor total: Float?

        def initialize: (
          invoice_id: String,
          period: String?,
          status: String?,
          total: Float?
        ) -> void

        def to_hash: -> {
          invoice_id: String,
          period: String?,
          status: String?,
          total: Float?
        }
      end

      type pagination = { next_offset: String? }

      class Pagination < VitableConnect::Internal::Type::BaseModel
        attr_accessor next_offset: String?

        def initialize: (next_offset: String?) -> void

        def to_hash: -> { next_offset: String? }
      end
    end
  end
end
