module VitableConnect
  module Models
    type employee_update_params =
      {
        employee_id: String,
        address: VitableConnect::EmployeeUpdateParams::Address?,
        email: String?,
        employee_class: VitableConnect::Models::employee_class?,
        gender: String?,
        phone: String?,
        termination_date: Date?
      }
      & VitableConnect::Internal::Type::request_parameters

    class EmployeeUpdateParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor employee_id: String

      attr_accessor address: VitableConnect::EmployeeUpdateParams::Address?

      attr_accessor email: String?

      attr_accessor employee_class: VitableConnect::Models::employee_class?

      attr_accessor gender: String?

      attr_accessor phone: String?

      attr_accessor termination_date: Date?

      def initialize: (
        employee_id: String,
        ?address: VitableConnect::EmployeeUpdateParams::Address?,
        ?email: String?,
        ?employee_class: VitableConnect::Models::employee_class?,
        ?gender: String?,
        ?phone: String?,
        ?termination_date: Date?,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        employee_id: String,
        address: VitableConnect::EmployeeUpdateParams::Address?,
        email: String?,
        employee_class: VitableConnect::Models::employee_class?,
        gender: String?,
        phone: String?,
        termination_date: Date?,
        request_options: VitableConnect::RequestOptions
      }

      type address =
        {
          city: String,
          state: String,
          :street_1 => String,
          zip_code: String,
          country: String,
          :street_2 => String?
        }

      class Address < VitableConnect::Internal::Type::BaseModel
        attr_accessor city: String

        attr_accessor state: String

        attr_accessor street_1: String

        attr_accessor zip_code: String

        attr_reader country: String?

        def country=: (String) -> String

        attr_accessor street_2: String?

        def initialize: (
          city: String,
          state: String,
          street_1: String,
          zip_code: String,
          ?country: String,
          ?street_2: String?
        ) -> void

        def to_hash: -> {
          city: String,
          state: String,
          :street_1 => String,
          zip_code: String,
          country: String,
          :street_2 => String?
        }
      end
    end
  end
end
