module VitableConnect
  module Models
    type employee_list_enrollments_response =
      {
        data: ::Array[VitableConnect::Enrollment],
        pagination: VitableConnect::Pagination
      }

    class EmployeeListEnrollmentsResponse < VitableConnect::Internal::Type::BaseModel
      attr_accessor data: ::Array[VitableConnect::Enrollment]

      attr_accessor pagination: VitableConnect::Pagination

      def initialize: (
        data: ::Array[VitableConnect::Enrollment],
        pagination: VitableConnect::Pagination
      ) -> void

      def to_hash: -> {
        data: ::Array[VitableConnect::Enrollment],
        pagination: VitableConnect::Pagination
      }
    end
  end
end
