module VitableConnect
  module Models
    type employer_list_benefit_plan_year_enrollments_params =
      {
        employer_id: String,
        benefit_plan_year_id: String,
        election_status: ::Array[VitableConnect::Models::EmployerListBenefitPlanYearEnrollmentsParams::election_status],
        limit: Integer,
        page: Integer,
        search: String
      }
      & VitableConnect::Internal::Type::request_parameters

    class EmployerListBenefitPlanYearEnrollmentsParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor employer_id: String

      attr_accessor benefit_plan_year_id: String

      attr_reader election_status: ::Array[VitableConnect::Models::EmployerListBenefitPlanYearEnrollmentsParams::election_status]?

      def election_status=: (
        ::Array[VitableConnect::Models::EmployerListBenefitPlanYearEnrollmentsParams::election_status]
      ) -> ::Array[VitableConnect::Models::EmployerListBenefitPlanYearEnrollmentsParams::election_status]

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader page: Integer?

      def page=: (Integer) -> Integer

      attr_reader search: String?

      def search=: (String) -> String

      def initialize: (
        employer_id: String,
        benefit_plan_year_id: String,
        ?election_status: ::Array[VitableConnect::Models::EmployerListBenefitPlanYearEnrollmentsParams::election_status],
        ?limit: Integer,
        ?page: Integer,
        ?search: String,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        employer_id: String,
        benefit_plan_year_id: String,
        election_status: ::Array[VitableConnect::Models::EmployerListBenefitPlanYearEnrollmentsParams::election_status],
        limit: Integer,
        page: Integer,
        search: String,
        request_options: VitableConnect::RequestOptions
      }

      type election_status = :Enrolled | :Expired | :Pending | :Waived

      module ElectionStatus
        extend VitableConnect::Internal::Type::Enum

        ENROLLED: :Enrolled
        EXPIRED: :Expired
        PENDING: :Pending
        WAIVED: :Waived

        def self?.values: -> ::Array[VitableConnect::Models::EmployerListBenefitPlanYearEnrollmentsParams::election_status]
      end
    end
  end
end
