module VitableConnect
  module Models
    type employee =
      {
        id: String,
        classification_effective_date: Date,
        compensation_type: VitableConnect::Models::Employee::compensation_type?,
        compensation_type_effective_date: Date,
        created_at: Time,
        date_of_birth: Date,
        deductions: ::Array[VitableConnect::Employee::Deduction],
        email: String,
        employee_class: VitableConnect::Models::employee_class,
        employer_id: String,
        first_name: String,
        last_name: String,
        member_id: String,
        phone: String?,
        start_date: Date,
        status: VitableConnect::Models::Employee::status,
        updated_at: Time,
        address: VitableConnect::Employee::Address?,
        employer_name: String?,
        gender: String?,
        reference_id: String?,
        suffix: String?,
        termination_date: Date?
      }

    class Employee < VitableConnect::Internal::Type::BaseModel
      attr_accessor created_at: Time

      attr_accessor date_of_birth: Date

      attr_accessor deductions: ::Array[VitableConnect::Employee::Deduction]

      attr_accessor email: String

      attr_accessor employee_class: VitableConnect::Models::employee_class

      attr_accessor first_name: String

      attr_accessor last_name: String

      attr_accessor updated_at: Time

      attr_accessor address: VitableConnect::Employee::Address?

      attr_accessor employer_name: String?

      attr_accessor gender: String?

      attr_accessor reference_id: String?

      attr_accessor suffix: String?

      attr_accessor termination_date: Date?

      attr_accessor id: String

      attr_accessor classification_effective_date: Date

      attr_accessor compensation_type: VitableConnect::Models::Employee::compensation_type?

      attr_accessor compensation_type_effective_date: Date

      attr_accessor employer_id: String

      attr_accessor member_id: String

      attr_accessor phone: String?

      attr_accessor start_date: Date

      attr_accessor status: VitableConnect::Models::Employee::status

      def initialize: (
        id: String,
        classification_effective_date: Date,
        compensation_type: VitableConnect::Models::Employee::compensation_type?,
        compensation_type_effective_date: Date,
        created_at: Time,
        date_of_birth: Date,
        deductions: ::Array[VitableConnect::Employee::Deduction],
        email: String,
        employee_class: VitableConnect::Models::employee_class,
        employer_id: String,
        first_name: String,
        last_name: String,
        member_id: String,
        phone: String?,
        start_date: Date,
        status: VitableConnect::Models::Employee::status,
        updated_at: Time,
        ?address: VitableConnect::Employee::Address?,
        ?employer_name: String?,
        ?gender: String?,
        ?reference_id: String?,
        ?suffix: String?,
        ?termination_date: Date?
      ) -> void

      def to_hash: -> {
        id: String,
        classification_effective_date: Date,
        compensation_type: VitableConnect::Models::Employee::compensation_type?,
        compensation_type_effective_date: Date,
        created_at: Time,
        date_of_birth: Date,
        deductions: ::Array[VitableConnect::Employee::Deduction],
        email: String,
        employee_class: VitableConnect::Models::employee_class,
        employer_id: String,
        first_name: String,
        last_name: String,
        member_id: String,
        phone: String?,
        start_date: Date,
        status: VitableConnect::Models::Employee::status,
        updated_at: Time,
        address: VitableConnect::Employee::Address?,
        employer_name: String?,
        gender: String?,
        reference_id: String?,
        suffix: String?,
        termination_date: Date?
      }

      type compensation_type = :Salary | :Hourly

      module CompensationType
        extend VitableConnect::Internal::Type::Enum

        SALARY: :Salary
        HOURLY: :Hourly

        def self?.values: -> ::Array[VitableConnect::Models::Employee::compensation_type]
      end

      type deduction =
        {
          benefit_name: String,
          deduction_amount_in_cents: Integer,
          deduction_category: String?,
          frequency: VitableConnect::Models::Employee::Deduction::frequency,
          period_end_date: Date,
          period_start_date: Date,
          tax_classification: VitableConnect::Models::Employee::Deduction::tax_classification
        }

      class Deduction < VitableConnect::Internal::Type::BaseModel
        attr_accessor benefit_name: String

        attr_accessor deduction_amount_in_cents: Integer

        attr_accessor deduction_category: String?

        attr_accessor frequency: VitableConnect::Models::Employee::Deduction::frequency

        attr_accessor period_end_date: Date

        attr_accessor period_start_date: Date

        attr_accessor tax_classification: VitableConnect::Models::Employee::Deduction::tax_classification

        def initialize: (
          benefit_name: String,
          deduction_amount_in_cents: Integer,
          deduction_category: String?,
          frequency: VitableConnect::Models::Employee::Deduction::frequency,
          period_end_date: Date,
          period_start_date: Date,
          tax_classification: VitableConnect::Models::Employee::Deduction::tax_classification
        ) -> void

        def to_hash: -> {
          benefit_name: String,
          deduction_amount_in_cents: Integer,
          deduction_category: String?,
          frequency: VitableConnect::Models::Employee::Deduction::frequency,
          period_end_date: Date,
          period_start_date: Date,
          tax_classification: VitableConnect::Models::Employee::Deduction::tax_classification
        }

        type frequency = :weekly | :bi_weekly | :semi_monthly | :monthly

        module Frequency
          extend VitableConnect::Internal::Type::Enum

          WEEKLY: :weekly
          BI_WEEKLY: :bi_weekly
          SEMI_MONTHLY: :semi_monthly
          MONTHLY: :monthly

          def self?.values: -> ::Array[VitableConnect::Models::Employee::Deduction::frequency]
        end

        type tax_classification = :Unknown | :"Pre-tax" | :"Post-tax"

        module TaxClassification
          extend VitableConnect::Internal::Type::Enum

          UNKNOWN: :Unknown
          PRE_TAX: :"Pre-tax"
          POST_TAX: :"Post-tax"

          def self?.values: -> ::Array[VitableConnect::Models::Employee::Deduction::tax_classification]
        end
      end

      type status = :active | :terminated

      module Status
        extend VitableConnect::Internal::Type::Enum

        ACTIVE: :active
        TERMINATED: :terminated

        def self?.values: -> ::Array[VitableConnect::Models::Employee::status]
      end

      type address =
        {
          :address_line_1 => String,
          city: String,
          state: String,
          zipcode: String,
          :address_line_2 => String?
        }

      class Address < VitableConnect::Internal::Type::BaseModel
        attr_accessor address_line_1: String

        attr_accessor city: String

        attr_accessor state: String

        attr_accessor zipcode: String

        attr_accessor address_line_2: String?

        def initialize: (
          address_line_1: String,
          city: String,
          state: String,
          zipcode: String,
          ?address_line_2: String?
        ) -> void

        def to_hash: -> {
          :address_line_1 => String,
          city: String,
          state: String,
          zipcode: String,
          :address_line_2 => String?
        }
      end
    end
  end
end
