module VitableConnect
  module Models
    type employer_list_params =
      {
        benefit_family: ::Array[VitableConnect::Models::EmployerListParams::benefit_family],
        benefit_lifecycle_stage: ::Array[VitableConnect::Models::EmployerListParams::benefit_lifecycle_stage],
        hris_status: ::Array[VitableConnect::Models::EmployerListParams::hris_status],
        include_cancelled: bool,
        limit: Integer,
        page: Integer,
        search: String?
      }
      & VitableConnect::Internal::Type::request_parameters

    class EmployerListParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_reader benefit_family: ::Array[VitableConnect::Models::EmployerListParams::benefit_family]?

      def benefit_family=: (
        ::Array[VitableConnect::Models::EmployerListParams::benefit_family]
      ) -> ::Array[VitableConnect::Models::EmployerListParams::benefit_family]

      attr_reader benefit_lifecycle_stage: ::Array[VitableConnect::Models::EmployerListParams::benefit_lifecycle_stage]?

      def benefit_lifecycle_stage=: (
        ::Array[VitableConnect::Models::EmployerListParams::benefit_lifecycle_stage]
      ) -> ::Array[VitableConnect::Models::EmployerListParams::benefit_lifecycle_stage]

      attr_reader hris_status: ::Array[VitableConnect::Models::EmployerListParams::hris_status]?

      def hris_status=: (
        ::Array[VitableConnect::Models::EmployerListParams::hris_status]
      ) -> ::Array[VitableConnect::Models::EmployerListParams::hris_status]

      attr_reader include_cancelled: bool?

      def include_cancelled=: (bool) -> bool

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader page: Integer?

      def page=: (Integer) -> Integer

      attr_accessor search: String?

      def initialize: (
        ?benefit_family: ::Array[VitableConnect::Models::EmployerListParams::benefit_family],
        ?benefit_lifecycle_stage: ::Array[VitableConnect::Models::EmployerListParams::benefit_lifecycle_stage],
        ?hris_status: ::Array[VitableConnect::Models::EmployerListParams::hris_status],
        ?include_cancelled: bool,
        ?limit: Integer,
        ?page: Integer,
        ?search: String?,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        benefit_family: ::Array[VitableConnect::Models::EmployerListParams::benefit_family],
        benefit_lifecycle_stage: ::Array[VitableConnect::Models::EmployerListParams::benefit_lifecycle_stage],
        hris_status: ::Array[VitableConnect::Models::EmployerListParams::hris_status],
        include_cancelled: bool,
        limit: Integer,
        page: Integer,
        search: String?,
        request_options: VitableConnect::RequestOptions
      }

      type benefit_family = :mec | :mvp | :ichra | :vpc | :dental | :vision

      module BenefitFamily
        extend VitableConnect::Internal::Type::Enum

        MEC: :mec
        MVP: :mvp
        ICHRA: :ichra
        VPC: :vpc
        DENTAL: :dental
        VISION: :vision

        def self?.values: -> ::Array[VitableConnect::Models::EmployerListParams::benefit_family]
      end

      type benefit_lifecycle_stage =
        :open_enrollment | :renewal | :active | :onboarding | :cancelled

      module BenefitLifecycleStage
        extend VitableConnect::Internal::Type::Enum

        OPEN_ENROLLMENT: :open_enrollment
        RENEWAL: :renewal
        ACTIVE: :active
        ONBOARDING: :onboarding
        CANCELLED: :cancelled

        def self?.values: -> ::Array[VitableConnect::Models::EmployerListParams::benefit_lifecycle_stage]
      end

      type hris_status = :Pending | :Active | :Inactive | :Paused | :Terminated

      module HRISStatus
        extend VitableConnect::Internal::Type::Enum

        PENDING: :Pending
        ACTIVE: :Active
        INACTIVE: :Inactive
        PAUSED: :Paused
        TERMINATED: :Terminated

        def self?.values: -> ::Array[VitableConnect::Models::EmployerListParams::hris_status]
      end
    end
  end
end
