module VitableConnect
  module Models
    type enrollment_list_plans_response =
      {
        data: ::Array[VitableConnect::Models::EnrollmentListPlansResponse::Data],
        pagination: VitableConnect::Pagination
      }

    class EnrollmentListPlansResponse < VitableConnect::Internal::Type::BaseModel
      attr_accessor data: ::Array[VitableConnect::Models::EnrollmentListPlansResponse::Data]

      attr_accessor pagination: VitableConnect::Pagination

      def initialize: (
        data: ::Array[VitableConnect::Models::EnrollmentListPlansResponse::Data],
        pagination: VitableConnect::Pagination
      ) -> void

      def to_hash: -> {
        data: ::Array[VitableConnect::Models::EnrollmentListPlansResponse::Data],
        pagination: VitableConnect::Pagination
      }

      type data =
        {
          id: String,
          costs: ::Array[VitableConnect::Models::EnrollmentListPlansResponse::Data::Cost],
          name: String,
          carrier_name: String?,
          deductible_cents: Integer?,
          description: String?,
          out_of_pocket_max_cents: Integer?,
          tier: VitableConnect::Models::plan_tier?
        }

      class Data < VitableConnect::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor costs: ::Array[VitableConnect::Models::EnrollmentListPlansResponse::Data::Cost]

        attr_accessor name: String

        attr_accessor carrier_name: String?

        attr_accessor deductible_cents: Integer?

        attr_accessor description: String?

        attr_accessor out_of_pocket_max_cents: Integer?

        attr_accessor tier: VitableConnect::Models::plan_tier?

        def initialize: (
          id: String,
          costs: ::Array[VitableConnect::Models::EnrollmentListPlansResponse::Data::Cost],
          name: String,
          ?carrier_name: String?,
          ?deductible_cents: Integer?,
          ?description: String?,
          ?out_of_pocket_max_cents: Integer?,
          ?tier: VitableConnect::Models::plan_tier?
        ) -> void

        def to_hash: -> {
          id: String,
          costs: ::Array[VitableConnect::Models::EnrollmentListPlansResponse::Data::Cost],
          name: String,
          carrier_name: String?,
          deductible_cents: Integer?,
          description: String?,
          out_of_pocket_max_cents: Integer?,
          tier: VitableConnect::Models::plan_tier?
        }

        type cost =
          {
            coverage_tier: VitableConnect::Models::coverage_tier,
            employee_contribution_cents: Integer,
            employer_contribution_cents: Integer,
            total_monthly_premium_cents: Integer
          }

        class Cost < VitableConnect::Internal::Type::BaseModel
          attr_accessor coverage_tier: VitableConnect::Models::coverage_tier

          attr_accessor employee_contribution_cents: Integer

          attr_accessor employer_contribution_cents: Integer

          attr_accessor total_monthly_premium_cents: Integer

          def initialize: (
            coverage_tier: VitableConnect::Models::coverage_tier,
            employee_contribution_cents: Integer,
            employer_contribution_cents: Integer,
            total_monthly_premium_cents: Integer
          ) -> void

          def to_hash: -> {
            coverage_tier: VitableConnect::Models::coverage_tier,
            employee_contribution_cents: Integer,
            employer_contribution_cents: Integer,
            total_monthly_premium_cents: Integer
          }
        end
      end
    end
  end
end
