module VitableConnect
  module Models
    type enrollment_list_plans_params =
      {  } & VitableConnect::Internal::Type::request_parameters

    class EnrollmentListPlansParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      def initialize: (?request_options: VitableConnect::request_opts) -> void

      def to_hash: -> { request_options: VitableConnect::RequestOptions }
    end
  end
end
