module VitableConnect
  module Models
    type enrollment_retrieve_params =
      { enrollment_id: String }
      & VitableConnect::Internal::Type::request_parameters

    class EnrollmentRetrieveParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor enrollment_id: String

      def initialize: (
        enrollment_id: String,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        enrollment_id: String,
        request_options: VitableConnect::RequestOptions
      }
    end
  end
end
