module VitableConnect
  module Models
    type enrollment_reissue_response =
      { data: VitableConnect::Models::EnrollmentReissueResponse::Data }

    class EnrollmentReissueResponse < VitableConnect::Internal::Type::BaseModel
      attr_accessor data: VitableConnect::Models::EnrollmentReissueResponse::Data

      def initialize: (
        data: VitableConnect::Models::EnrollmentReissueResponse::Data
      ) -> void

      def to_hash: -> {
        data: VitableConnect::Models::EnrollmentReissueResponse::Data
      }

      type data = { enrollment_id: String }

      class Data < VitableConnect::Internal::Type::BaseModel
        attr_accessor enrollment_id: String

        def initialize: (enrollment_id: String) -> void

        def to_hash: -> { enrollment_id: String }
      end
    end
  end
end
