module VitableConnect
  module Models
    type enrollment_reissue_params =
      { enrollment_id: String, qle_id: String, reason: String? }
      & VitableConnect::Internal::Type::request_parameters

    class EnrollmentReissueParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor enrollment_id: String

      attr_accessor qle_id: String

      attr_accessor reason: String?

      def initialize: (
        enrollment_id: String,
        qle_id: String,
        ?reason: String?,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        enrollment_id: String,
        qle_id: String,
        reason: String?,
        request_options: VitableConnect::RequestOptions
      }
    end
  end
end
