module VitableConnect
  module Models
    type enrollment_retrieve_response = { data: VitableConnect::Enrollment }

    class EnrollmentRetrieveResponse < VitableConnect::Internal::Type::BaseModel
      attr_accessor data: VitableConnect::Enrollment

      def initialize: (data: VitableConnect::Enrollment) -> void

      def to_hash: -> { data: VitableConnect::Enrollment }
    end
  end
end
