module VitableConnect
  module Models
    type group_list_params =
      { limit: Integer, page: Integer }
      & VitableConnect::Internal::Type::request_parameters

    class GroupListParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader page: Integer?

      def page=: (Integer) -> Integer

      def initialize: (
        ?limit: Integer,
        ?page: Integer,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        limit: Integer,
        page: Integer,
        request_options: VitableConnect::RequestOptions
      }
    end
  end
end
