module VitableConnect
  module Models
    type member_list_enrollments_response =
      {
        data: ::Array[VitableConnect::Models::MemberListEnrollmentsResponse::Data]
      }

    class MemberListEnrollmentsResponse < VitableConnect::Internal::Type::BaseModel
      attr_accessor data: ::Array[VitableConnect::Models::MemberListEnrollmentsResponse::Data]

      def initialize: (
        data: ::Array[VitableConnect::Models::MemberListEnrollmentsResponse::Data]
      ) -> void

      def to_hash: -> {
        data: ::Array[VitableConnect::Models::MemberListEnrollmentsResponse::Data]
      }

      type data =
        {
          id: String,
          benefit_plan_year_id: String,
          benefit_type: VitableConnect::Models::MemberListEnrollmentsResponse::Data::benefit_type,
          cancelled_date: Date?,
          election_status: VitableConnect::Models::MemberListEnrollmentsResponse::Data::election_status,
          employer_id: String,
          employer_name: String,
          enrollment_window_start: Date,
          in_last_month_of_coverage: bool,
          is_within_enrollment_window: bool,
          issued_date: Date,
          plan_year_coverage_end: Date?,
          policy_status: VitableConnect::Models::MemberListEnrollmentsResponse::Data::policy_status?,
          product_code: VitableConnect::Models::MemberListEnrollmentsResponse::Data::product_code,
          product_name: String,
          requires_qle_for_reissue: bool,
          carrier_name: String?,
          coverage_end: Date?,
          coverage_start: Date?,
          employee_deduction_in_cents: Integer?,
          employer_contribution_in_cents: Integer?,
          enrollment_window_end: Date?,
          plan_name: String?,
          premium_in_cents: Integer?,
          tier_name: String?
        }

      class Data < VitableConnect::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor benefit_plan_year_id: String

        attr_accessor benefit_type: VitableConnect::Models::MemberListEnrollmentsResponse::Data::benefit_type

        attr_accessor cancelled_date: Date?

        attr_accessor election_status: VitableConnect::Models::MemberListEnrollmentsResponse::Data::election_status

        attr_accessor employer_id: String

        attr_accessor employer_name: String

        attr_accessor enrollment_window_start: Date

        attr_accessor in_last_month_of_coverage: bool

        attr_accessor is_within_enrollment_window: bool

        attr_accessor issued_date: Date

        attr_accessor plan_year_coverage_end: Date?

        attr_accessor policy_status: VitableConnect::Models::MemberListEnrollmentsResponse::Data::policy_status?

        attr_accessor product_code: VitableConnect::Models::MemberListEnrollmentsResponse::Data::product_code

        attr_accessor product_name: String

        attr_accessor requires_qle_for_reissue: bool

        attr_accessor carrier_name: String?

        attr_accessor coverage_end: Date?

        attr_accessor coverage_start: Date?

        attr_accessor employee_deduction_in_cents: Integer?

        attr_accessor employer_contribution_in_cents: Integer?

        attr_accessor enrollment_window_end: Date?

        attr_accessor plan_name: String?

        attr_accessor premium_in_cents: Integer?

        attr_accessor tier_name: String?

        def initialize: (
          id: String,
          benefit_plan_year_id: String,
          benefit_type: VitableConnect::Models::MemberListEnrollmentsResponse::Data::benefit_type,
          cancelled_date: Date?,
          election_status: VitableConnect::Models::MemberListEnrollmentsResponse::Data::election_status,
          employer_id: String,
          employer_name: String,
          enrollment_window_start: Date,
          in_last_month_of_coverage: bool,
          is_within_enrollment_window: bool,
          issued_date: Date,
          plan_year_coverage_end: Date?,
          policy_status: VitableConnect::Models::MemberListEnrollmentsResponse::Data::policy_status?,
          product_code: VitableConnect::Models::MemberListEnrollmentsResponse::Data::product_code,
          product_name: String,
          requires_qle_for_reissue: bool,
          ?carrier_name: String?,
          ?coverage_end: Date?,
          ?coverage_start: Date?,
          ?employee_deduction_in_cents: Integer?,
          ?employer_contribution_in_cents: Integer?,
          ?enrollment_window_end: Date?,
          ?plan_name: String?,
          ?premium_in_cents: Integer?,
          ?tier_name: String?
        ) -> void

        def to_hash: -> {
          id: String,
          benefit_plan_year_id: String,
          benefit_type: VitableConnect::Models::MemberListEnrollmentsResponse::Data::benefit_type,
          cancelled_date: Date?,
          election_status: VitableConnect::Models::MemberListEnrollmentsResponse::Data::election_status,
          employer_id: String,
          employer_name: String,
          enrollment_window_start: Date,
          in_last_month_of_coverage: bool,
          is_within_enrollment_window: bool,
          issued_date: Date,
          plan_year_coverage_end: Date?,
          policy_status: VitableConnect::Models::MemberListEnrollmentsResponse::Data::policy_status?,
          product_code: VitableConnect::Models::MemberListEnrollmentsResponse::Data::product_code,
          product_name: String,
          requires_qle_for_reissue: bool,
          carrier_name: String?,
          coverage_end: Date?,
          coverage_start: Date?,
          employee_deduction_in_cents: Integer?,
          employer_contribution_in_cents: Integer?,
          enrollment_window_end: Date?,
          plan_name: String?,
          premium_in_cents: Integer?,
          tier_name: String?
        }

        type benefit_type = :Medical | :Dental | :Vision | :Hospital

        module BenefitType
          extend VitableConnect::Internal::Type::Enum

          MEDICAL: :Medical
          DENTAL: :Dental
          VISION: :Vision
          HOSPITAL: :Hospital

          def self?.values: -> ::Array[VitableConnect::Models::MemberListEnrollmentsResponse::Data::benefit_type]
        end

        type election_status = :Enrolled | :Waived | :Pending | :Expired

        module ElectionStatus
          extend VitableConnect::Internal::Type::Enum

          ENROLLED: :Enrolled
          WAIVED: :Waived
          PENDING: :Pending
          EXPIRED: :Expired

          def self?.values: -> ::Array[VitableConnect::Models::MemberListEnrollmentsResponse::Data::election_status]
        end

        type policy_status =
          :"Coverage Upcoming"
          | :"Coverage Effective"
          | :"Coverage Ended"
          | :Cancelled

        module PolicyStatus
          extend VitableConnect::Internal::Type::Enum

          COVERAGE_UPCOMING: :"Coverage Upcoming"
          COVERAGE_EFFECTIVE: :"Coverage Effective"
          COVERAGE_ENDED: :"Coverage Ended"
          CANCELLED: :Cancelled

          def self?.values: -> ::Array[VitableConnect::Models::MemberListEnrollmentsResponse::Data::policy_status]
        end

        type product_code =
          :EBA
          | :VPC
          | :VPC_CORE
          | :MEC
          | :MEC2
          | :MEC_PLUS
          | :MVP
          | :MVP2
          | :MVPSL
          | :MVPSL2
          | :VD
          | :VV
          | :ICHRA
          | :ICHRA_PREMIUM_PLUS
          | :ICHRA_REIMBURSEMENT_ONLY

        module ProductCode
          extend VitableConnect::Internal::Type::Enum

          EBA: :EBA
          VPC: :VPC
          VPC_CORE: :VPC_CORE
          MEC: :MEC
          MEC2: :MEC2
          MEC_PLUS: :MEC_PLUS
          MVP: :MVP
          MVP2: :MVP2
          MVPSL: :MVPSL
          MVPSL2: :MVPSL2
          VD: :VD
          VV: :VV
          ICHRA: :ICHRA
          ICHRA_PREMIUM_PLUS: :ICHRA_PREMIUM_PLUS
          ICHRA_REIMBURSEMENT_ONLY: :ICHRA_REIMBURSEMENT_ONLY

          def self?.values: -> ::Array[VitableConnect::Models::MemberListEnrollmentsResponse::Data::product_code]
        end
      end
    end
  end
end
