module VitableConnect
  module Models
    type member_list_dependents_response =
      {
        data: ::Array[VitableConnect::Models::MemberListDependentsResponse::Data]
      }

    class MemberListDependentsResponse < VitableConnect::Internal::Type::BaseModel
      attr_accessor data: ::Array[VitableConnect::Models::MemberListDependentsResponse::Data]

      def initialize: (
        data: ::Array[VitableConnect::Models::MemberListDependentsResponse::Data]
      ) -> void

      def to_hash: -> {
        data: ::Array[VitableConnect::Models::MemberListDependentsResponse::Data]
      }

      type data =
        {
          age: Integer,
          date_of_birth: Date,
          first_name: String,
          last_name: String,
          member_id: String,
          primary_member_id: String,
          relationship: VitableConnect::Models::MemberListDependentsResponse::Data::relationship,
          sex_at_birth: VitableConnect::Models::MemberListDependentsResponse::Data::sex_at_birth?
        }

      class Data < VitableConnect::Internal::Type::BaseModel
        attr_accessor age: Integer

        attr_accessor date_of_birth: Date

        attr_accessor first_name: String

        attr_accessor last_name: String

        attr_accessor relationship: VitableConnect::Models::MemberListDependentsResponse::Data::relationship

        attr_accessor sex_at_birth: VitableConnect::Models::MemberListDependentsResponse::Data::sex_at_birth?

        attr_accessor member_id: String

        attr_accessor primary_member_id: String

        def initialize: (
          age: Integer,
          date_of_birth: Date,
          first_name: String,
          last_name: String,
          member_id: String,
          primary_member_id: String,
          relationship: VitableConnect::Models::MemberListDependentsResponse::Data::relationship,
          ?sex_at_birth: VitableConnect::Models::MemberListDependentsResponse::Data::sex_at_birth?
        ) -> void

        def to_hash: -> {
          age: Integer,
          date_of_birth: Date,
          first_name: String,
          last_name: String,
          member_id: String,
          primary_member_id: String,
          relationship: VitableConnect::Models::MemberListDependentsResponse::Data::relationship,
          sex_at_birth: VitableConnect::Models::MemberListDependentsResponse::Data::sex_at_birth?
        }

        type relationship = :Spouse | :Child

        module Relationship
          extend VitableConnect::Internal::Type::Enum

          SPOUSE: :Spouse
          CHILD: :Child

          def self?.values: -> ::Array[VitableConnect::Models::MemberListDependentsResponse::Data::relationship]
        end

        type sex_at_birth = :Male | :Female | :Other | :Unknown

        module SexAtBirth
          extend VitableConnect::Internal::Type::Enum

          MALE: :Male
          FEMALE: :Female
          OTHER: :Other
          UNKNOWN: :Unknown

          def self?.values: -> ::Array[VitableConnect::Models::MemberListDependentsResponse::Data::sex_at_birth]
        end
      end
    end
  end
end
