module VitableConnect
  module Models
    type member_retrieve_params =
      { member_id: String } & VitableConnect::Internal::Type::request_parameters

    class MemberRetrieveParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor member_id: String

      def initialize: (
        member_id: String,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        member_id: String,
        request_options: VitableConnect::RequestOptions
      }
    end
  end
end
