module VitableConnect
  module Models
    type member_list_id_cards_response =
      { data: ::Array[VitableConnect::Models::MemberListIDCardsResponse::Data] }

    class MemberListIDCardsResponse < VitableConnect::Internal::Type::BaseModel
      attr_accessor data: ::Array[VitableConnect::Models::MemberListIDCardsResponse::Data]

      def initialize: (
        data: ::Array[VitableConnect::Models::MemberListIDCardsResponse::Data]
      ) -> void

      def to_hash: -> {
        data: ::Array[VitableConnect::Models::MemberListIDCardsResponse::Data]
      }

      type data =
        {
          card_type: VitableConnect::Models::MemberListIDCardsResponse::Data::card_type,
          group_id: String,
          group_member_id: String,
          member_name: String,
          nsa_table: ::Array[::Array[String]],
          benefit_code: VitableConnect::Models::MemberListIDCardsResponse::Data::benefit_code?,
          carrier_phone: String?,
          carrier_website: String?,
          claims_payer_display_name: String?,
          employer_name: String?,
          general_disclaimer: String?,
          network: VitableConnect::Models::MemberListIDCardsResponse::Data::Network?,
          plan_disclaimer: String?,
          plan_name: String?
        }

      class Data < VitableConnect::Internal::Type::BaseModel
        attr_accessor card_type: VitableConnect::Models::MemberListIDCardsResponse::Data::card_type

        attr_accessor group_id: String

        attr_accessor group_member_id: String

        attr_accessor member_name: String

        attr_accessor nsa_table: ::Array[::Array[String]]

        attr_accessor benefit_code: VitableConnect::Models::MemberListIDCardsResponse::Data::benefit_code?

        attr_accessor carrier_phone: String?

        attr_accessor carrier_website: String?

        attr_accessor claims_payer_display_name: String?

        attr_accessor employer_name: String?

        attr_accessor general_disclaimer: String?

        attr_accessor network: VitableConnect::Models::MemberListIDCardsResponse::Data::Network?

        attr_accessor plan_disclaimer: String?

        attr_accessor plan_name: String?

        def initialize: (
          card_type: VitableConnect::Models::MemberListIDCardsResponse::Data::card_type,
          group_id: String,
          group_member_id: String,
          member_name: String,
          nsa_table: ::Array[::Array[String]],
          ?benefit_code: VitableConnect::Models::MemberListIDCardsResponse::Data::benefit_code?,
          ?carrier_phone: String?,
          ?carrier_website: String?,
          ?claims_payer_display_name: String?,
          ?employer_name: String?,
          ?general_disclaimer: String?,
          ?network: VitableConnect::Models::MemberListIDCardsResponse::Data::Network?,
          ?plan_disclaimer: String?,
          ?plan_name: String?
        ) -> void

        def to_hash: -> {
          card_type: VitableConnect::Models::MemberListIDCardsResponse::Data::card_type,
          group_id: String,
          group_member_id: String,
          member_name: String,
          nsa_table: ::Array[::Array[String]],
          benefit_code: VitableConnect::Models::MemberListIDCardsResponse::Data::benefit_code?,
          carrier_phone: String?,
          carrier_website: String?,
          claims_payer_display_name: String?,
          employer_name: String?,
          general_disclaimer: String?,
          network: VitableConnect::Models::MemberListIDCardsResponse::Data::Network?,
          plan_disclaimer: String?,
          plan_name: String?
        }

        type card_type = :medical | :dental | :vision | :rx

        module CardType
          extend VitableConnect::Internal::Type::Enum

          MEDICAL: :medical
          DENTAL: :dental
          VISION: :vision
          RX: :rx

          def self?.values: -> ::Array[VitableConnect::Models::MemberListIDCardsResponse::Data::card_type]
        end

        type benefit_code =
          :EBA
          | :VPC
          | :VPC_CORE
          | :MEC
          | :MEC2
          | :MEC_PLUS
          | :MVP
          | :MVP2
          | :MVPSL
          | :MVPSL2
          | :VD
          | :VV
          | :ICHRA
          | :ICHRA_PREMIUM_PLUS
          | :ICHRA_REIMBURSEMENT_ONLY

        module BenefitCode
          extend VitableConnect::Internal::Type::Enum

          EBA: :EBA
          VPC: :VPC
          VPC_CORE: :VPC_CORE
          MEC: :MEC
          MEC2: :MEC2
          MEC_PLUS: :MEC_PLUS
          MVP: :MVP
          MVP2: :MVP2
          MVPSL: :MVPSL
          MVPSL2: :MVPSL2
          VD: :VD
          VV: :VV
          ICHRA: :ICHRA
          ICHRA_PREMIUM_PLUS: :ICHRA_PREMIUM_PLUS
          ICHRA_REIMBURSEMENT_ONLY: :ICHRA_REIMBURSEMENT_ONLY

          def self?.values: -> ::Array[VitableConnect::Models::MemberListIDCardsResponse::Data::benefit_code]
        end

        type network =
          {
            id: String,
            address: VitableConnect::Models::MemberListIDCardsResponse::Data::Network::Address,
            logo: String?,
            member_phone: String?,
            name: String,
            phone: String,
            provider_phone: String?,
            website: String,
            edi: String?,
            member_website: String?,
            provider_website: String?
          }

        class Network < VitableConnect::Internal::Type::BaseModel
          attr_accessor address: VitableConnect::Models::MemberListIDCardsResponse::Data::Network::Address

          attr_accessor logo: String?

          attr_accessor member_phone: String?

          attr_accessor name: String

          attr_accessor phone: String

          attr_accessor provider_phone: String?

          attr_accessor website: String

          attr_accessor edi: String?

          attr_accessor member_website: String?

          attr_accessor provider_website: String?

          attr_accessor id: String

          def initialize: (
            id: String,
            address: VitableConnect::Models::MemberListIDCardsResponse::Data::Network::Address,
            logo: String?,
            member_phone: String?,
            name: String,
            phone: String,
            provider_phone: String?,
            website: String,
            ?edi: String?,
            ?member_website: String?,
            ?provider_website: String?
          ) -> void

          def to_hash: -> {
            id: String,
            address: VitableConnect::Models::MemberListIDCardsResponse::Data::Network::Address,
            logo: String?,
            member_phone: String?,
            name: String,
            phone: String,
            provider_phone: String?,
            website: String,
            edi: String?,
            member_website: String?,
            provider_website: String?
          }

          type address =
            {
              :address_line_1 => String,
              :address_line_2 => String?,
              city: String,
              state: String,
              zipcode: String
            }

          class Address < VitableConnect::Internal::Type::BaseModel
            attr_accessor address_line_1: String

            attr_accessor address_line_2: String?

            attr_accessor city: String

            attr_accessor state: String

            attr_accessor zipcode: String

            def initialize: (
              address_line_1: String,
              address_line_2: String?,
              city: String,
              state: String,
              zipcode: String
            ) -> void

            def to_hash: -> {
              :address_line_1 => String,
              :address_line_2 => String?,
              city: String,
              state: String,
              zipcode: String
            }
          end
        end
      end
    end
  end
end
