module VitableConnect
  module Models
    type member_list_qualifying_life_events_params =
      {
        member_id: String,
        limit: Integer,
        page: Integer,
        status: VitableConnect::Models::MemberListQualifyingLifeEventsParams::status
      }
      & VitableConnect::Internal::Type::request_parameters

    class MemberListQualifyingLifeEventsParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor member_id: String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader page: Integer?

      def page=: (Integer) -> Integer

      attr_reader status: VitableConnect::Models::MemberListQualifyingLifeEventsParams::status?

      def status=: (
        VitableConnect::Models::MemberListQualifyingLifeEventsParams::status
      ) -> VitableConnect::Models::MemberListQualifyingLifeEventsParams::status

      def initialize: (
        member_id: String,
        ?limit: Integer,
        ?page: Integer,
        ?status: VitableConnect::Models::MemberListQualifyingLifeEventsParams::status,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        member_id: String,
        limit: Integer,
        page: Integer,
        status: VitableConnect::Models::MemberListQualifyingLifeEventsParams::status,
        request_options: VitableConnect::RequestOptions
      }

      type status = :approved | :denied | :pending

      module Status
        extend VitableConnect::Internal::Type::Enum

        APPROVED: :approved
        DENIED: :denied
        PENDING: :pending

        def self?.values: -> ::Array[VitableConnect::Models::MemberListQualifyingLifeEventsParams::status]
      end
    end
  end
end
