module VitableConnect
  module Models
    type member_list_qualifying_life_events_response =
      {
        id: String,
        event_type: VitableConnect::Models::MemberListQualifyingLifeEventsResponse::event_type,
        other_event: String?,
        status: VitableConnect::Models::MemberListQualifyingLifeEventsResponse::status,
        submitted_at: Time
      }

    class MemberListQualifyingLifeEventsResponse < VitableConnect::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor event_type: VitableConnect::Models::MemberListQualifyingLifeEventsResponse::event_type

      attr_accessor other_event: String?

      attr_accessor status: VitableConnect::Models::MemberListQualifyingLifeEventsResponse::status

      attr_accessor submitted_at: Time

      def initialize: (
        id: String,
        event_type: VitableConnect::Models::MemberListQualifyingLifeEventsResponse::event_type,
        other_event: String?,
        status: VitableConnect::Models::MemberListQualifyingLifeEventsResponse::status,
        submitted_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        event_type: VitableConnect::Models::MemberListQualifyingLifeEventsResponse::event_type,
        other_event: String?,
        status: VitableConnect::Models::MemberListQualifyingLifeEventsResponse::status,
        submitted_at: Time
      }

      type event_type =
        :Married | :Divorced | :"New child" | :"Court ordered" | :Other

      module EventType
        extend VitableConnect::Internal::Type::Enum

        MARRIED: :Married
        DIVORCED: :Divorced
        NEW_CHILD: :"New child"
        COURT_ORDERED: :"Court ordered"
        OTHER: :Other

        def self?.values: -> ::Array[VitableConnect::Models::MemberListQualifyingLifeEventsResponse::event_type]
      end

      type status = :pending | :approved | :denied

      module Status
        extend VitableConnect::Internal::Type::Enum

        PENDING: :pending
        APPROVED: :approved
        DENIED: :denied

        def self?.values: -> ::Array[VitableConnect::Models::MemberListQualifyingLifeEventsResponse::status]
      end
    end
  end
end
