module VitableConnect
  module Models
    type organization_create_params =
      {
        name: String,
        type: VitableConnect::Models::OrganizationCreateParams::type_?
      }
      & VitableConnect::Internal::Type::request_parameters

    class OrganizationCreateParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor name: String

      attr_accessor type: VitableConnect::Models::OrganizationCreateParams::type_?

      def initialize: (
        name: String,
        ?type: VitableConnect::Models::OrganizationCreateParams::type_?,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        name: String,
        type: VitableConnect::Models::OrganizationCreateParams::type_?,
        request_options: VitableConnect::RequestOptions
      }

      type type_ =
        :BROKERAGE
        | :TPA
        | :GENERAL_AGENT
        | :CHANNEL_PARTNER
        | :CONSULTING_FIRM
        | :API_PLATFORM

      module Type
        extend VitableConnect::Internal::Type::Enum

        BROKERAGE: :BROKERAGE
        TPA: :TPA
        GENERAL_AGENT: :GENERAL_AGENT
        CHANNEL_PARTNER: :CHANNEL_PARTNER
        CONSULTING_FIRM: :CONSULTING_FIRM
        API_PLATFORM: :API_PLATFORM

        def self?.values: -> ::Array[VitableConnect::Models::OrganizationCreateParams::type_]
      end
    end
  end
end
