module VitableConnect
  module Models
    type plan_year_retrieve_params =
      { plan_year_id: String }
      & VitableConnect::Internal::Type::request_parameters

    class PlanYearRetrieveParams < VitableConnect::Internal::Type::BaseModel
      extend VitableConnect::Internal::Type::RequestParameters::Converter
      include VitableConnect::Internal::Type::RequestParameters

      attr_accessor plan_year_id: String

      def initialize: (
        plan_year_id: String,
        ?request_options: VitableConnect::request_opts
      ) -> void

      def to_hash: -> {
        plan_year_id: String,
        request_options: VitableConnect::RequestOptions
      }
    end
  end
end
