module VitableConnect
  module Models
    type sex = :Male | :Female | :Other | :Unknown

    module Sex
      extend VitableConnect::Internal::Type::Enum

      MALE: :Male
      FEMALE: :Female
      OTHER: :Other
      UNKNOWN: :Unknown

      def self?.values: -> ::Array[VitableConnect::Models::sex]
    end
  end
end
